pulp/pulp-operator

- deploy/crds/pulpproject_v1alpha1_pulp_cr.yaml
- deploy/operator.yaml
- roles/pulp-content/defaults/main.yml
I tested it successfully on Minikube: Both pulp-content pods are serving content.
I also included a minor cleanup fix
https://etherpad.net/p/Pulp_K8s_Operator_TODO (Medium-term & later tasks will be put on redmine instead.)
> Increase pulp-content replicas from 1 to 2

- .travis.yml
- .travis/pulp-operator-check-and-wait.sh
- deploy/operator.yaml
https://pulp.plan.io/issues/5174
_pulp-operator CI should automatically build its image for k3s testing_
fixes #5174
https://pulp.plan.io/issues/5174
> Automatically build the operator in CI

- .travis.yml
- .travis/pulp-operator-check-and-wait.sh
- .travis/pulp_file-tests.sh
- deploy/operator.yaml
- roles/pulp-api/templates/pulp-api.deployment.yaml
- roles/pulp-content/templates/pulp-content.deployment.yaml
- roles/pulp-resource-manager/templates/pulp-resource-manager.deployment.yaml
- roles/pulp-worker/templates/pulp-worker.deployment.yaml
"Fix using the entrypoint script" is the commit that fixes Fedora container support (the bug is not Fedora-specific, but is harmless on the CentOS containers currently.)
re: #5176
https://pulp.plan.io/issues/5176
"Port pulp containers to Fedora 30"
> Fix support for Fedora pulp containers & other fixes/debugging improvements

- .travis/k3s-install.sh
So that built & cached images can be used later during CI.
This means that the pulp-operator CI now actually tests the current
version of the image it builds, rather than the version from quay.
re: #5062
[Create pulpcore and pulp_file container images automatically via CI](https://pulp.plan.io/issues/5062)
> Use Docker rather than k3s-bundled containerd

- .travis.yml
- .travis/pulp_file-tests.sh
being run against stable release of pulp_file.
Solution: Try the newest tag for pulp_file if the master branch fails.
[noissue]
> Problem: Travis CI is failing due to master branch pulp_file tests

- deploy/cluster_role.yaml
- deploy/cluster_role_binding.yaml
- deploy/crds/pulpproject_v1alpha1_pulp_cr.default.yaml
- deploy/role.yaml
- down.sh
- playbook.yml
- roles/pulp-api/tasks/get_node_ip.yml
- roles/pulp-api/tasks/main.yml
- up.sh
If not set by the user.
Limited scope (single-node clusters), but sufficient for
minikube/k3s/our Travis CI.
fixes: #5138
In pulp-operator, the content_origin should be set to the actual accessible service URL
https://pulp.plan.io/issues/5138
re: #5629
[Epic] Introduce CONTENT_ORIGIN as a required setting
https://pulp.plan.io/issues/5629
> Set content_origin to the 1st node's 1st address.

- .travis.yml
- insta-demo/Vagrantfile
About 2-3 months ago, k3s failed to start.
Now, due to either our changes or k3s's is, it does.
plugin-template task:
re: 5156
Update travis to run on ubuntu b18.04
https://pulp.plan.io/issues/5156
[noissue]
> Travis Ubuntu 18.04 support

- deploy/crds/pulpproject_v1alpha1_pulp_cr.default.yaml
- deploy/crds/pulpproject_v1alpha1_pulp_cr.travis.yaml
Was due to k3s interpreting the 3.0 image tag as 3 due to lack of quotes.
And therefore thinking the image does not exist (ImagePullBackoff)
Solution: Put quotes around the tag in all the cr.yaml files here,
even though their strings do not require them.
[noissue]
> Problem: pulpcore 3.0 CI was failing

- .travis.yml
- deploy/operator.yaml
- molecule/test-local/playbook.yml
Doing it, CI could catch if the new ansible-operator version has a breaking change
-----------------------------------------------------------------------------------------------------
`/bin/ao-logs` was removed on v0.18.0:
https://github.com/operator-framework/operator-sdk/blob/191d79824df3db82f98bd8e658551d0f846fe8f5/website/content/en/docs/migration/v0.18.0.md#remove-the-file-binao-logs-for-ansible-based-operators
How to migrate:
https://github.com/operator-framework/operator-sdk/blob/e128b9e5d147ef43fbca46b8ddb5037a9b1e3cbd/website/content/en/docs/migration/version-upgrade-guide.md
> Always get the latest operator version

- build/Dockerfile
Currently, the CI is getting v0.17.2 because it is the latest release.
https://github.com/operator-framework/operator-sdk/releases
We want to get the most recent one (which is v0.18.2)
> Update ansible-operator image

- .travis.yml
- .travis/deploy.sh
- .travis/vars.yaml
5 months ago was last time `pulp` image was pushed - https://quay.io/repository/pulp/pulp?tag=latest&tab=tags
it is using:
```json
"versions": [
{
"component": "pulpcore",
"version": "3.0.1"
},
{
"component": "pulp_rpm",
"version": "3.0.0"
},
{
"component": "pulp_python",
"version": "3.0.0b8"
},
{
"component": "pulp_maven",
"version": "0.1.0b3"
},
{
"component": "pulp_file",
"version": "0.1.0"
},
{
"component": "pulp_cookbook",
"version": "0.1.0b5"
},
{
"component": "pulp_container",
"version": "1.0.0"
},
{
"component": "pulp_certguard",
"version": "0.1.0rc3.dev0"
},
{
"component": "pulp_ansible",
"version": "0.2.0b7"
}
]
```
> Build and publish pulp container

- .travis/molecule.sh
- CHANGES/7107.misc
- molecule/default/prepare.yml
https://pulp.plan.io/issues/7107
closes #7107
From:
http://www.thinkcode.se/blog/2019/02/20/kubernetes-service-node-port-range
> Change molecule NodePort range

- .ci/scripts/deploy.sh
- .ci/scripts/quay-push.sh
- .github/workflows/pr.yml
- insta-demo/pulp-insta-demo.sh
Deploy fails because it tries docker push when it should use podman
```
TASK [Check for podman] ********************************************************
changed: [localhost] => changed=true 
cmd:
- which
- podman
delta: '0:00:00.002599'
end: '2021-01-13 13:16:52.542464'
rc: 0
start: '2021-01-13 13:16:52.539865'
stderr: ''
stderr_lines: <omitted>
stdout: /usr/bin/podman
stdout_lines: <omitted>
TASK [set_fact] ****************************************************************
ok: [localhost] => changed=false 
ansible_facts:
container_cli: podman
```
https://github.com/pulp/pulp-operator/runs/1695146929?check_suite_focus=true#step:8:4084
> Use podman when deploying

- .ci/scripts/deploy.sh
- .ci/scripts/quay-push.sh
- insta-demo/pulp-insta-demo.sh
pulp-operator image is built with docker, with the operator machinery.
While pulp and pulpcore images are built with podman.
[noissue]
> Enable to choose between docker and podman when deploying

- CHANGES/5141.misc
- roles/postgres/templates/postgres.deployment.yaml.j2
Persistent volume will be accessed with UID and group associated with postgres as defined in the image
fixes #5141
https://pulp.plan.io/issues/5141
> Add security context fsGroup to deployment of postgres container

- CHANGES/5142.misc
- roles/pulp-api/templates/pulp-api.deployment.yaml.j2
- roles/pulp-content/templates/pulp-content.deployment.yaml.j2
- roles/pulp-resource-manager/templates/pulp-resource-manager.deployment.yaml.j2
- roles/pulp-worker/templates/pulp-worker.deployment.yaml.j2
Add security context runAsUser and fsGroup to deployments interacting with pulp-file-storage PVC
fixes #5142
https://pulp.plan.io/issues/5142
> Add security context to deployments interacting with pulp-file-storage PVC

- .ci/scripts/pulp-operator-check-and-wait.sh
- CHANGES/8345.misc
- playbook.yml
- roles/pulp-api/templates/pulp-api.deployment.yaml.j2
- roles/pulp-content/templates/pulp-content.deployment.yaml.j2
- roles/pulp-resource-manager/templates/pulp-resource-manager.deployment.yaml.j2
- roles/pulp-worker/templates/pulp-worker.deployment.yaml.j2
- roles/redis/defaults/main.yml
- roles/redis/templates/redis.deployment.yaml.j2
- roles/redis/templates/redis.service.yaml.j2
* Move redis image to "redis:latest" aligning with other operators
* Parameterize deployment and service using CR naming
* Update consuming deployments with host & port informaiton
closes #8345
https://pulp.plan.io/issues/8345
> Deploy standard redis image with CR naming convention.

- .ci/assets/kubernetes/pulp-admin-password.secret.yaml
- CHANGES/8353.misc
- deploy/crds/pulpproject_v1beta1_pulp_cr.ci.yaml
- deploy/crds/pulpproject_v1beta1_pulp_cr.default.yaml
- deploy/crds/pulpproject_v1beta1_pulp_crd.yaml
- down.sh
- roles/pulp-api/defaults/main.yml
- roles/pulp-api/tasks/admin_password_configuration.yml
- roles/pulp-api/tasks/main.yml
- roles/pulp-api/templates/pulp-admin-password.secret.yaml.j2
- roles/pulp-api/templates/pulp-api.deployment.yaml.j2
- roles/redis/templates/redis.deployment.yaml.j2
- up.sh
* Add option to specify the secret in the CRD
* Add tasks to check or generate the secret
* Update API deployment to use the value from the secret
closes #8353
https://pulp.plan.io/issues/8353
> Set or generate admin password with kubernetes secret.

- .ci/scripts/pulp-operator-check-and-wait.sh
- .github/workflows/ci.yml
- .github/workflows/pr.yml
- CHANGES/8361.feature
- containers/images/pulp/Containerfile.core.j2
- containers/images/pulp/container-assets/pulp-api
- deploy/crds/pulpproject_v1beta1_pulp_cr.ci.yaml
- deploy/crds/pulpproject_v1beta1_pulp_cr.default.yaml
- deploy/crds/pulpproject_v1beta1_pulp_cr.pulp-demo.yaml
- deploy/crds/pulpproject_v1beta1_pulp_crd.yaml
- playbook.yml
- roles/pulp-api/README.md
- roles/pulp-api/defaults/main.yml
- roles/pulp-api/tasks/azure-storage-configuration.yml
- roles/pulp-api/tasks/main.yml
- roles/pulp-api/tasks/s3-storage-configuration.yml
- roles/pulp-api/templates/pulp-api.deployment.yaml.j2
- roles/pulp-api/templates/pulp-file-storage.pvc.yaml.j2
- roles/pulp-content/templates/pulp-content.deployment.yaml.j2
- roles/pulp-resource-manager/templates/pulp-resource-manager.deployment.yaml.j2
- roles/pulp-worker/templates/pulp-worker.deployment.yaml.j2
* Update container with both storage options
* Update CRD with object storage configuration via secret
* Add roles to configure settings.py based on object storage secret
* Do not create and bind PVC if object storage is used
closes #8361
https://pulp.plan.io/issues/8361
> Enable the use of S3 compliant or Azure object storage as storage backend

- .ci/assets/kubernetes/pulp-object-storage.aws.secret.yaml
- .ci/assets/kubernetes/pulp-object-storage.azure.secret.yaml
- .gitignore
- CHANGES/8399.misc
- containers/images/pulp/Containerfile.web.j2
- deploy/crds/pulpproject_v1beta1_pulp_cr.galaxy.ci.yaml
- deploy/crds/pulpproject_v1beta1_pulp_cr.object_storage.aws.yaml
- deploy/crds/pulpproject_v1beta1_pulp_cr.object_storage.azure.yaml
- deploy/crds/pulpproject_v1beta1_pulp_crd.yaml
- roles/pulp-web/defaults/main.yml
- roles/pulp-web/templates/pulp-web.configmap.yaml.j2
- up.sh
* Include static file in galaxy-web image
* Update CRD to supply web image
* Add example CRs to simplify testing
* Update up.sh to simplify deployment testing
fixes #8399
https://pulp.plan.io/issues/8399
> Enable the deployment of galaxy via CR with web content

- CHANGES/8424.bugfix
- roles/pulp-api/tasks/main.yml
* Correct storage option check logic
fixes #8424
https://pulp.plan.io/issues/8424
> Fix storage option check so that Azure Blob Storage can be used as a backend

- roles/redis/templates/redis.deployment.yaml.j2
- roles/redis/templates/redis.pvc.yaml.j2
This PR fixes the following issues that were happening in the redis pod
```
24 Mar 2021 10:21:16.062 # Failed opening the RDB file dump.rdb (in
server root dir /data) for saving: Permission denied
24 Mar 2021 10:21:16.162 # Background saving error
```
As it is written today. PVC is always made with `redis-data` name and
does not take in consideration the deployment name. This allows for
multiple deployment of pulp in single namespace.
[noissue]
> Redis: Fix Permission denied and multiple deployment in same namespace

- roles/pulp-api/templates/pulp-api.deployment.yaml.j2
- roles/pulp-web/templates/pulp-web.configmap.yaml.j2
[noissue]
Uploading a collection on OCP with object storage hit the following error on the API pod:
Fix nginx to logging output (was not displaying before):
> Fix upload /var/lib/pulp/temp Permission Denied and nginx logging

- deploy/olm-catalog/pulp-operator/manifests/pulp-operator.clusterserviceversion.yaml
- deploy/operator.yaml
The liveness probes default are too agressive and can lead to
undeployable operators[1][2] - We are bumping them as per the
operator-sdk default in 1.0[3]
[1] https://github.com/operator-framework/operator-sdk/issues/3216
[2] https://github.com/operator-framework/operator-sdk/issues/3267
[3]
https://github.com/operator-framework/operator-sdk/commit/ea43495073a543ede5f10ea5790660004cf750be
[noissue]
> Update liveness probe defaults

- CHANGES/8456.feature
- deploy/crds/pulpproject_v1beta1_pulp_cr.ci.yaml
- deploy/crds/pulpproject_v1beta1_pulp_crd.yaml
- deploy/olm-catalog/pulp-operator/manifests/pulp-operator.clusterserviceversion.yaml
- deploy/olm-catalog/pulp-operator/manifests/pulp.pulpproject.org_pulps_crd.yml
- roles/pulp-api/defaults/main.yml
- roles/pulp-api/tasks/get_node_ip.yml
- roles/pulp-api/templates/pulp-api.deployment.yaml.j2
- roles/pulp-content/defaults/main.yml
- roles/pulp-content/templates/pulp-content.deployment.yaml.j2
- roles/pulp-resource-manager/defaults/main.yml
- roles/pulp-resource-manager/templates/pulp-resource-manager.deployment.yaml.j2
- roles/pulp-routes/tasks/main.yml
- roles/pulp-status/tasks/main.yml
- roles/pulp-web/defaults/main.yml
- roles/pulp-web/templates/pulp-web.deployment.yaml.j2
- roles/pulp-worker/defaults/main.yml
- roles/pulp-worker/templates/pulp-worker.deployment.yaml.j2
- roles/redis/defaults/main.yml
- roles/redis/templates/redis.deployment.yaml.j2
* Update CRD
* Update UI display in cluster version
* Add resource requirements specification to defaults and deployments
* Add checks for needed inputs during ingress and route deployments
* Add pod running check for web server and successful health check for successful reconciliation
fixes #8456
https://pulp.plan.io/issues/8456
> Enable resource req specification and have operator do health check

- roles/pulp-api/templates/pulp-api.deployment.yaml.j2
* Add access to /var/lib/pulp/assets when file storage isn't in use
[noissue]
> Permission error hit for static assets when using object storage

- deploy/olm-catalog/pulp-operator/manifests/pulp-operator.clusterserviceversion.yaml
* Highlight pulp storage choice for user; default to File
* Only make ReadWriteMany selectable from the UI as RWO is for single node clusters only
[noissue]
> Move pulp storage options into regular settings

- CHANGES/8472.feature
- deploy/crds/pulpproject_v1beta1_pulp_crd.yaml
- deploy/olm-catalog/pulp-operator/manifests/pulp-operator.clusterserviceversion.yaml
- deploy/olm-catalog/pulp-operator/manifests/pulp.pulpproject.org_pulps_crd.yml
- deploy/role.yaml
- roles/postgres/defaults/main.yml
- roles/postgres/tasks/main.yml
- roles/postgres/tasks/migrate_data.yml
- roles/postgres/tasks/scale_down.yml
- roles/postgres/templates/postgres.yaml.j2
- roles/pulp-api/templates/pulp-api.deployment.yaml.j2
- roles/pulp-api/templates/pulp-api.service.yaml.j2
- roles/pulp-api/templates/pulp-file-storage.pvc.yaml.j2
- roles/pulp-content/templates/pulp-content.deployment.yaml.j2
- roles/pulp-content/templates/pulp-content.service.yaml.j2
- roles/pulp-resource-manager/templates/pulp-resource-manager.deployment.yaml.j2
- roles/pulp-status/defaults/main.yml
- roles/pulp-status/tasks/main.yml
- roles/pulp-web/templates/pulp-web.deployment.yaml.j2
- roles/pulp-web/templates/pulp-web.service.yaml.j2
- roles/pulp-worker/templates/pulp-worker.deployment.yaml.j2
- roles/redis/templates/redis.deployment.yaml.j2
- roles/redis/templates/redis.service.yaml.j2
* Add support for container based database migration via CR
* Update operator role to enable command execution on a pod
* Add check to postgres role around migration
* Add migration of data tasks
* Add scale down tasks
* Update status role to record db migration
* Misc. fix for conflicting label selectors
fixes #8472
https://pulp.plan.io/issues/8472
> Enable container based database migration support

- .ci/scripts/deploy.sh
- .github/workflows/ci.yml
- CHANGES/8530.misc
- containers/images/pulp/Containerfile.core.j2
- containers/images/pulp/Containerfile.web.j2
* Add optional label to each of the images that allows quay to automatically prune images.
* Add ci step to get the latest release tag
* Set QUAY_IMAGE_TAG to latest release tag + the day of the year
* Set QUAY_EXPIRE to 14 to keep images for 2 weeks initially
* Run publish again where new environment variables should publish expiring images
fixes #8530
https://pulp.plan.io/issues/8530
Reference: https://docs.projectquay.io/use_quay.html#tag-expiration
> Enable nightly expiring container builds

- CHANGES/8598.misc
- deploy/crds/pulpproject_v1beta1_pulp_cr.galaxy.container.ci.yaml
- deploy/crds/pulpproject_v1beta1_pulp_crd.yaml
- deploy/crds/pulpproject_v1beta1_pulpbackup_crd.yaml
- deploy/olm-catalog/pulp-operator/manifests/pulp-operator.clusterserviceversion.yaml
- deploy/olm-catalog/pulp-operator/manifests/pulp.pulpproject.org_pulpbackups_crd.yml
- deploy/olm-catalog/pulp-operator/manifests/pulp.pulpproject.org_pulps_crd.yml
- playbook.yml
- roles/backup/tasks/init.yml
- roles/backup/tasks/secrets.yml
- roles/backup/tasks/update_status.yml
- roles/backup/templates/container_token_secret.yaml.j2
- roles/pulp-api/tasks/get_node_ip.yml
- roles/pulp-api/templates/pulp-api.deployment.yaml.j2
- roles/pulp-status/tasks/main.yml
- roles/restore/tasks/init.yml
- roles/restore/tasks/secrets.yml
- roles/restore/templates/container_token_secret.yaml.j2
- up.sh
* Update CRD with container token secret
* Update CRD with settings
* Add playbook defaults
* Setup token server value
* Mount container auth keys when secret is provided
* Provide galaxy container CR for testing
* Add secret to status of Pulp and PulpBackup
* Write secret during backup
* Read/Create secret during restore
fixes #8598
https://pulp.plan.io/issues/8598
> Container registry capabilities will be disable by default in Galaxy

- deploy/crds/pulpproject_v1beta1_pulp_crd.yaml
- deploy/olm-catalog/pulp-operator/manifests/pulp-operator.clusterserviceversion.yaml
- deploy/olm-catalog/pulp-operator/manifests/pulp.pulpproject.org_pulps_crd.yml
- roles/postgres/templates/postgres.yaml.j2
- roles/pulp-api/templates/pulp-api.deployment.yaml.j2
- roles/pulp-content/templates/pulp-content.deployment.yaml.j2
- roles/pulp-resource-manager/templates/pulp-resource-manager.deployment.yaml.j2
- roles/pulp-web/templates/pulp-web.deployment.yaml.j2
- roles/pulp-worker/templates/pulp-worker.deployment.yaml.j2
- roles/redis/templates/redis.deployment.yaml.j2
* Update CRD to allow for pull policy and node affinity
* Update deployments for pull policy and node affinity
[noissue]
This work allows an user to select `Always` as a pull policy to obtain the latest container image on pod deployment (meant to enable testing more easily).
The [node affinity capability ](https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes-using-node-affinity/)allows a user to specify a node of the deployments to run on. This could allow users to target nodes with specific disk storage capabilities or specify node labels like infra nodes for subscription related reasons down stream.
> Provide image pull policy or node affinity for deployment

- .ci/ansible/galaxy/vars.yaml
- .ci/ansible/vars.yaml
Galaxy doesn't have an upper bound on pulp_container
https://github.com/ansible/galaxy_ng/blob/master/setup.py#L66
pulp_container@master requires pulpcore >= 3.12.1
https://github.com/pulp/pulp_container/blob/master/requirements.txt#L1
> Fix galaxy image

- deploy/olm-catalog/pulp-operator/manifests/pulp-operator.clusterserviceversion.yaml
- playbook.yml
- roles/pulp-api/tasks/get_node_ip.yml
* Update CSV to hide field by default
* Remove container registry settings from defaults
* Add container registry settings when secret is provided
[noissue]
> Only add container registry settings if container secret is provided.

- deploy/crds/pulpproject_v1beta1_pulpbackup_crd.yaml
- deploy/crds/pulpproject_v1beta1_pulprestore_crd.yaml
- deploy/olm-catalog/pulp-operator/manifests/pulp-operator.clusterserviceversion.yaml
- deploy/olm-catalog/pulp-operator/manifests/pulp.pulpproject.org_pulpbackups_crd.yml
- deploy/olm-catalog/pulp-operator/manifests/pulp.pulpproject.org_pulprestores_crd.yml
Both backup and restore are currently using the oneOf spec in the CRD in
an invalid way, leading to invalid UI.
On the backup crd just using required is enough to accomplish original
goal.
On the restore crd its a bit tricky as more business logic is embeded.
[noissue]
> Restructure operator restore variable presentation

- roles/postgres/tasks/migrate_data.yml
* This approach is compatible with the RH postgresql container and postgres container
[noissue]
Pull in bug fix: https://github.com/ansible/awx-operator/pull/296
> Use custom archive format when migrating data

- roles/pulp-api/templates/pulp-file-storage.pvc.yaml.j2
By default this variable is not defined leading to deployment to fail if
not provided. This should be applied only if defined.
Issue raised
```
TASK [pulp-file-storage persistent volume claim] ******************************** 
[0;31mfatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'size'\n\nThe error appears to be in '/opt/ansible/roles/pulp-api/tasks/main.yml': line 20, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: pulp-file-storage persistent volume claim\n  ^ here\n"}[0m
```
[noissue]
> file_storage.size: Specify it only when defined

- CHANGES/8733.bugfix
- roles/postgres/defaults/main.yml
- roles/postgres/templates/postgres.yaml.j2
* Update defaults
* Update jinja2 condition in template
fixes #8733
https://pulp.plan.io/issues/8733
> Allow user to specify empty string storage class for postgres PVC.

- deploy/olm-catalog/pulp-operator/manifests/pulp-operator.clusterserviceversion.yaml
Operator seems to complain if installed via OLM. Your CSV seems to be missing some permissions from [`cluster_role.yaml`](https://github.com/pulp/pulp-operator/blob/main/deploy/cluster_role.yaml)
Pod logs:
```
E0518 14:15:23.426471       8 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list /v1, Kind=Node: nodes is forbidden: User "system:serviceaccount:openshift-operators:pulp-operator" cannot list resource "nodes" in API group "" at the cluster scope
E0518 14:16:22.921909       8 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list /v1, Kind=Node: nodes is forbidden: User "system:serviceaccount:openshift-operators:pulp-operator" cannot list resource "nodes" in API group "" at the cluster scope
```
> fix: CSV cluster role for nodes

- playbook.yml
- roles/pulp-api/tasks/get_node_ip.yml
* If the user doesn't supply route_host then the operator didn't know how to set CONTENT_ORIGIN properly when ingress_type is route
* Create the route first
* Check for the route information to populate the CONTENT_ORIGIN when ingress_type is route
[no issue]
> Create route in order to capture cluster default subdomain

- deploy/crds/pulpproject_v1beta1_pulp_cr.ci.yaml
- deploy/crds/pulpproject_v1beta1_pulp_cr.default.yaml
- deploy/crds/pulpproject_v1beta1_pulp_cr.galaxy.ci.yaml
- deploy/crds/pulpproject_v1beta1_pulp_cr.galaxy.container.ci.yaml
- deploy/crds/pulpproject_v1beta1_pulp_cr.pulp-demo.yaml
- deploy/crds/pulpproject_v1beta1_pulp_crd.yaml
- deploy/olm-catalog/pulp-operator/manifests/pulp-operator.clusterserviceversion.yaml
- deploy/olm-catalog/pulp-operator/manifests/pulp.pulpproject.org_pulps_crd.yml
- playbook.yml
- roles/pulp-api/README.md
- roles/pulp-api/templates/pulp-file-storage.pvc.yaml.j2
- roles/pulp-status/tasks/main.yml
* No longer using an object for file_storage
* Access mode, size and storage class are all top level options
[noissue]
Previous experience may lead users to miss additional configuration:
New experience presents options more clearly to users:
> Improve user experience in OperatorHub when choosing File Storage.

- .ci/scripts/galaxy_ng-tests.sh
- .ci/scripts/pulp-operator-check-and-wait.sh
- CHANGES/8833.bugfix
- deploy/crds/pulpproject_v1beta1_pulp_crd.yaml
- deploy/olm-catalog/pulp-operator/manifests/pulp-operator.clusterserviceversion.yaml
- deploy/olm-catalog/pulp-operator/manifests/pulp.pulpproject.org_pulps_crd.yml
- playbook.yml
- roles/pulp-api/tasks/get_node_ip.yml
- roles/pulp-api/templates/pulp-api.service.yaml.j2
- roles/pulp-content/templates/pulp-content.service.yaml.j2
- roles/pulp-web/tasks/main.yml
- roles/pulp-web/templates/pulp-web.deployment.yaml.j2
- roles/pulp-web/templates/pulp-web.service.yaml.j2
* Don't attempt nodeport settings if not selected
* Use status.hostIP from downward API to get node where web pod is running https://stackoverflow.com/a/52047845
* Only set nodeport for web service
* Allow user to specify nodeport or take cluster default in range
fixes #8833
https://pulp.plan.io/issues/8833
> Use nodeport flow only when defined, otherwise supply svc.cluster.local option

- deploy/operator.yaml
Created this PR so people using it can have visibility into changing the logs to debug when deploying if they wish.  This functionally changes nothing, just lets the user be aware of an environment var they cause use in order to get more detailed logging.
> Explicity defined ANSIBLE_DEBUG_LOGS environment variable

- roles/backup/tasks/init.yml
- backups are not supported when the pulp-content volume is
ReadWriteMany, the backup volume can be RWO
The current wording is a bit confusing and implies that the backup volume needs to be RWM, this clarifies that it can be RWO.
> Clarify RWM/O check during backups

- containers/images/pulp/container-assets/pulp-resource-manager
- containers/images/pulp/container-assets/pulp-worker
Current implementation is incorrect
```
$> export PATH /usr/local/bin:/usr/bin/
bash: export: `/usr/local/bin:/usr/bin/': not a valid identifier'`
```
[noissue]
> container-assets: Fix wrong bash syntax

- roles/backup/tasks/init.yml
- roles/postgres/tasks/main.yml
_customer_postgres_image should be set to postgres_image and not the
default _postgres_image
[noissue]
> Fix custom_postgres_image variable

- roles/backup/tasks/init.yml
- roles/postgres/tasks/main.yml
- roles/pulp-api/tasks/main.yml
- roles/pulp-content/tasks/main.yml
- roles/pulp-resource-manager/tasks/main.yml
- roles/pulp-web/tasks/main.yml
- roles/pulp-worker/tasks/main.yml
- roles/redis/tasks/main.yml
- roles/restore/tasks/init.yml
If custom image is not provided, and environment variable is not
provided, it ends up defaulting to '' in current state.
This commit fixes that.
[noissue]
https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#providing-default-values
Reproducer:
```
---
- hosts: localhost
gather_facts: false
vars:
_postgres_image: foo
tasks:
- debug:
msg: "{{ _custom_postgres_image | default(lookup('env', 'RELATED_IMAGE_PULP_POSTGRES')) | default(_postgres_image) }}"
- debug:
msg: "{{ _custom_postgres_image | default(lookup('env', 'RELATED_IMAGE_PULP_POSTGRES')) | default(_postgres_image, true) }}"
```
Output
```
PLAY [localhost] ************************************************************************************************************************
TASK [debug] …
```
> Use the default value when variables evaluate to an empty string

- roles/postgres/defaults/main.yml
- roles/postgres/tasks/main.yml
- roles/postgres/templates/postgres.yaml.j2
- roles/pulp-api/tasks/main.yml
- roles/pulp-api/templates/pulp-api.deployment.yaml.j2
- roles/pulp-content/defaults/main.yml
- roles/pulp-content/tasks/main.yml
- roles/pulp-content/templates/pulp-content.deployment.yaml.j2
- roles/pulp-resource-manager/defaults/main.yml
- roles/pulp-resource-manager/tasks/main.yml
- roles/pulp-resource-manager/templates/pulp-resource-manager.deployment.yaml.j2
- roles/pulp-web/defaults/main.yml
- roles/pulp-web/tasks/main.yml
- roles/pulp-web/templates/pulp-web.deployment.yaml.j2
- roles/pulp-worker/defaults/main.yml
- roles/pulp-worker/tasks/main.yml
- roles/pulp-worker/templates/pulp-worker.deployment.yaml.j2
- roles/redis/defaults/main.yml
- roles/redis/tasks/main.yml
- roles/redis/templates/redis.deployment.yaml.j2
* Obtain affinity from raw spec data
* If affinity and node_affinity are present apply to deployments
Affected by issue: https://github.com/operator-framework/operator-sdk/issues/1770
Related to: https://github.com/pulp/pulp-operator/issues/289
[noissue]
> Fix node affinity handling.

- containers/images/pulp/Containerfile.web.j2
Currently the container fails to start:
```console
$ podman run --rm quay.io/pulp/pulp-web:3.16.1
nginx: [emerg] "location" directive is not allowed here in /opt/app-root/etc/nginx.d/pulp_ansible.conf:1
```
Those custom nginx config files should be present in the
/opt/app-root/etc/nginx.default.d directory instead.
NGINX_CONFIGURATION_PATH -> config under the http section.
NGINX_DEFAULT_CONF_PATH -> config under the server section.
The `location` directive should be used in the server section.
[noissue]
> containers: fix nginx env var for pulp web

- roles/pulp-api/tasks/sso-configuration.yml
[noissue]
Signed-off-by: Julen Landa Alustiza <jlanda@redhat.com>
We are hardcoding [https](https://github.com/pulp/pulp-operator/blob/main/roles/pulp-api/tasks/get_node_ip.yml#L5) url here, but SSO tries to build the redirect_uri using http.
From https://python-social-auth.readthedocs.io/en/latest/configuration/settings.html:
> SOCIAL_AUTH_REDIRECT_IS_HTTPS = False
>
>    On projects behind a reverse proxy that uses HTTPS, the redirect URIs can have the wrong schema (http:// instead of https://) if the request lacks the appropriate headers, which might cause errors during the auth process. To force HTTPS in the final URIs set this setting to True
So hardcode this too during sso configuration
> Force https redirects while using SSO

- bundle/manifests/pulp-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
It appears that the memory limit of 256Mi can be easily reached in some cases. When this happens, the pulp-manager container restarts with OOMKill as the reason.  The end result to the user is that containers never come up.  This raises the limit significantly (2Gi).  Note, that this is only a limit, the operator will not actually use this much memory in most cases.
> Raise resource limits for operator container to avoid OOMKill

- bundle/manifests/pulp-operator.clusterserviceversion.yaml
- bundle/manifests/pulp.pulpproject.org_pulps.yaml
- config/crd/bases/pulpproject_v1beta1_pulp_crd.yaml
- config/manifests/bases/pulp-operator.clusterserviceversion.yaml
- roles/postgres/defaults/main.yml
- roles/postgres/tasks/main.yml
- roles/postgres/templates/postgres.yaml.j2
The pvc storage size is specified separately from the pod cpu & memory.  I also changed how this shows up in the OLM form so that unneeded fields from the resourceRequirements descriptor are not shown.  
Signed-off-by: Christian M. Adams <chadams@redhat.com>
> Split postgres resource and storage values into different vars

- Makefile
[noissue]
Ref: https://github.com/ansible/awx-operator/pull/766
> Take into account aarch64 architecture return from uname

- containers/images/pulp/Containerfile.core.j2
Without the quotes, you're just redirecting stdout to a file.
[noissue]
> Containerfile: fix django-storages version specifier

- CHANGES/343.feature
- config/crd/bases/pulpproject_v1beta1_pulp_crd.yaml
- config/manifests/bases/pulp-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- docs/roles/common.md
- mkdocs.yml
- molecule/default/tasks/pulp_test.yml
- molecule/default/verify.yml
- playbooks/pulp.yml
- roles/common/README.md
- roles/common/meta/main.yml
- roles/common/tasks/main.yml
- roles/common/templates/pulp-operator-sa.yaml.j2
- roles/postgres/templates/postgres.yaml.j2
- roles/pulp-api/templates/pulp-api.deployment.yaml.j2
- roles/pulp-content/templates/pulp-content.deployment.yaml.j2
- roles/pulp-resource-manager/templates/pulp-resource-manager.deployment.yaml.j2
- roles/pulp-web/templates/pulp-web.deployment.yaml.j2
- roles/pulp-worker/templates/pulp-worker.deployment.yaml.j2
- roles/redis/templates/redis.deployment.yaml.j2
Update image_pull_secret from string to image_pull_secrets array so
that users can now provide multiple secrets to pull images from
private registries.
fixes: #343
> Allow users to provide multiple pull secrets

- config/manager/manager.yaml
Follow-up change for https://github.com/pulp/pulp-operator/pull/383
@fao89 we decided to change the string name, sorry for the extra churn.
> Changed default pull secret to agreed upon name

- CHANGES/386.misc
- docs/doc_requirements.txt
Remove `pymdown-extention` from requirements.txt to leave the selection of the version of `pymdown-extention` to the dependency resolution for `mkdocs-material`.
closes #386
> Remove pymdown-extensions from doc_requirements.txt

- CHANGES/388.bugfix
- roles/pulp-status/tasks/main.yml
closes #388
Tested as follows:
```bash
$ IMG=registry.example.com/pulp/pulp-operator:0.9.1 make docker-build docker-push
$ IMG=registry.example.com/pulp/pulp-operator:0.9.1 make deploy
$ kubectl -n pulp apply -f galaxy.yml
$ kubectl -n pulp logs -f deployments/pulp-operator-controller-manager -c pulp-manager
```
The first attempt is exited with `failed=0` as expected. The issue #385 still remain, but #388 is solved.
```bash
$ kubectl -n pulp logs deployments/pulp-operator-controller-manager -c pulp-manager | grep "PLAY RECAP" -A 1
PLAY RECAP …
```
> Fix a reference to an incorrect variable in pulp-status role

- CHANGES/403.bugfix
- roles/pulp-api/tasks/container_auth_configuration.yml
- roles/pulp-api/tasks/main.yml
- Previously, a new secret was being created on each reconciliation
loop
fixes pulp#403
[noissue]
(cherry picked from commit 0312b669154927dc7c6fe7ae8fb62c6014b90034)
> Only create container auth secret if needed

- config/crd/bases/pulpproject_v1beta1_pulp_crd.yaml
- config/manifests/bases/pulp-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- config/testing/manager_image.yaml
- docs/roles/common.md
- molecule/default/tasks/pulp_test.yml
- molecule/kind/molecule.yml
- playbooks/pulp.yml
- roles/common/README.md
- roles/common/defaults/main.yml
- roles/common/meta/main.yml
- roles/common/tasks/main.yml
- roles/common/templates/pulp-operator-sa.yaml.j2
- roles/postgres/templates/postgres.yaml.j2
- roles/pulp-api/templates/pulp-api.deployment.yaml.j2
- roles/pulp-content/templates/pulp-content.deployment.yaml.j2
- roles/pulp-resource-manager/templates/pulp-resource-manager.deployment.yaml.j2
- roles/pulp-web/templates/pulp-web.deployment.yaml.j2
- roles/pulp-worker/templates/pulp-worker.deployment.yaml.j2
- roles/redis/templates/redis.deployment.yaml.j2
The OpenShift Controller Manager (OCM) ensures that the serviceaccounts
are synced with the secret to pull from the internal registry.
To handle this behavior - specific to OCP environments - this commit
allows configuring an image_pull_secrets variable to pull from private
registries without overwriting the secret added by OCM.
[noissue]
> Fix SA reconcile issue on OCP environments

- CHANGES/437.bugfix
- bundle/manifests/pulp.pulpproject.org_pulps.yaml
- config/crd/bases/pulpproject_v1beta1_pulp_crd.yaml
- containers/images/pulp/container-assets/pulp-api
- roles/pulp-api/defaults/main.yml
> Gunicorn API workers default to 2

- roles/pulp-status/tasks/main.yml
When upgrading from pulpcore < 3.16 then the resource manager deployment
is still present and in crashloop state since there's no entrypoint for
this service in the pulp container.
This ensures the pulp resource manager Deployment is absent when the core
version is >= 3.16
[noissue]
> Remove resource manager on upgrade

- config/samples/pulpproject_v1beta1_pulp_cr.default.yaml
It is possible to configure LDAP now via the galaxy_ng settings.  We should include an example of how to pass those settings via the `pulp_settings` field on the spec.  
We should probably also document this on the pulp-operator docs somewhere: https://docs.pulpproject.org/pulp_operator/quickstart/
We can link to https://galaxyng.netlify.app/integration/ldap/ for more details.
> Add commented LDAP settings to Pulp CR example

- config/rbac/role.yaml
- controllers/pulp/api.go
- controllers/pulp/content.go
- controllers/pulp/controller.go
- controllers/pulp/database.go
- controllers/pulp/redis.go
- controllers/pulp/route.go
- controllers/pulp/status.go
- controllers/pulp/web.go
- controllers/pulp/worker.go
Now it is also possible to watch/follow the operator events with:
```
$ kubectl get events --sort-by lastTimestamp --field-selector involvedObject.kind=Pulp -w
```
closes #517
> Add operator events

- controllers/pulp/api.go
it was adding a blank URL
```
~ via  v16.13.2 via 🐍 v3.10.4 (venv) 
❯ oc exec -it example-api-574b85c9b5-nxpkx  -- cat /etc/pulp/settings.py                                
AWS_S3_ENDPOINT_URL = ""
```
> Fix S3 config

- .ci/scripts/local.sh
- main.go
adding env vars to your debugger:
```json
{
"version": "0.2.0",
"configurations": [
{
"name": "Launch Operator",
"type": "go",
"request": "launch",
"mode": "auto",
"env": {
"DEV_MODE": "true"
},
"program": "${workspaceFolder}"
}
]
}
```
https://github.com/golang/vscode-go/wiki/debugging
> Dev mode logs to be enabled with env vars

- controllers/restore/deploy.go
A var used to store the number of worker replicas was receiving the number of web replicas.
[noissue]
> Fix wrong var attribution

- docs/quickstart.md
Seems to have been correct in the above line which starts with "Next, review ...".
> fix(docs): quickstart file path typo

- CHANGES/581.bugfix
- controllers/backup/secret.go
Before trying to backup a non-existent signing secret (which is optional) the controller will first check if it is defined in pulp CR.
fixes #581
> Fix issue with signing secret backup

- CHANGES/579.feature
- controllers/pulp/api.go
- controllers/pulp/content.go
- controllers/pulp/web.go
> Add readiness probe to pulp-web container

- api/v1alpha1/pulp_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
- controllers/pulp/README.md
- controllers/pulp/content.go
- controllers/pulp/redis.go
Some instructions were using the fields from API (nodeSelector and affinity) instead of using its own resource definition.
[noissue]
> Minor fix for nodeSelector and affinity check

- bundle/manifests/pulp-operator.clusterserviceversion.yaml
- bundle/manifests/pulp.pulpproject.org_pulpbackups.yaml
- config/manifests/bases/pulp-operator.clusterserviceversion.yaml
There has been some confusion about if the backup_pvc field should be set on PulpBackup's or not.  
This PR adds helper text that attempts to make it clearer that the backup_pvc should not be specified if the user wants a PVC to be automatically created for them.  It should only be specified if the user wants to pre-create the PVC instead of using a StorageClass.
> Add some guidance on how PulpBackup should be used

- config/crd/bases/pulpproject_v1beta1_pulp_crd.yaml
- Adding these defaults here breaks RELATED_IMAGE_ functionality
- We aleady have defaults in defaults.yml
> Remove default image values in spec to keep precedence order correct

- bundle/manifests/pulp-operator.clusterserviceversion.yaml
- config/manifests/bases/pulp-operator.clusterserviceversion.yaml
There were a couple form display issues resulting from these recent changes: https://github.com/pulp/pulp-operator/pull/644
These should be either advanced settings or hidden (deprecated):
This fixes them.
> Redis Form updates

- roles/pulp-api/templates/pulp-api.deployment.yaml.j2
- roles/pulp-content/templates/pulp-content.deployment.yaml.j2
- roles/pulp-web/templates/pulp-web.deployment.yaml.j2
- roles/pulp-worker/templates/pulp-worker.deployment.yaml.j2
- roles/redis/defaults/main.yml
- roles/redis/templates/redis.deployment.yaml.j2
The correct syntax for the default is actually:
```
redis:
strategy:
type: Recreate
```
If you fill it out in the form using the "deployment descriptor" it forces you to use this syntax.  As such, we need to also modify how this gets passed in the <component>.deployment.yml.j2 templates.  
I tested this out with the following in my spec.  Once the Pulp object was created, I checked to make sure the k8s validator didn't remove the strategy lines this time, it did not.  
```
spec:
...
redis:
log_level: INFO
replicas: 1
strategy:
type: Recreate
worker:
replicas: 1
resource_requirements:
requests:
cpu: 150m
memory: 256Mi
strategy:
type: Recreate
```
This now works as expected.  Here is the yaml on the resulting deployment object:
```
$ oc get deployment galaxy-demo-redis -o yaml | grep …
```
> Syntax fix for specifying redis deployment strategy default as recreate

- CHANGES/646.bugfix
- controllers/pulp/utils.go
Resources reconciled by this commit:
* Tolerations
* TopologySpreadConstraints
* ResourceRequirements
The usage of Semantic.DeepEqual method is helping to fix not only the field update, but also the field removal (for example, if the resource_requirements field was defined and removed after that it is now removing it from the deployment).
ref: #646
[noissue]
> Fixed more resources reconciliation

- roles/common/tasks/main.yml
Before the Route refact for removing the need of the web container when using OCP Route then the default route host was using the following parttern:
`<CR name>-<CR namespace>.<default domain>`
Now the pattern is using:
`<CR name>.<default domain>`
which breaks the backward compatibility when upgrading from a previous release.
[noissue]
> route: Ensure route_host backward compatibility

- CHANGES/646.bugfix
- controllers/repo_manager/redis.go
Resources reconciled by this commit:
* Tolerations
* NodeSelector
* ResourceRequirements
ref: #646
[noissue]
> Fix more redis resources reconciliation

- CHANGES/650.bugfix
- controllers/repo_manager/utils.go
From what I could understand, during an error condition we were calling the Status.Update() method in every retry of loop reconcile (even without anything needing to be changed).
This was kind of breaking the idempotency, so each time we called the Status.Update() method I think the controller thought that it was a new iteration, which caused the exponential backoff retry to not increment.
I'm not 100% sure if this will fix all of the "missing" exponential backoff retry.
fixes #650
> Fix "spamming" retry in case of error

- CHANGES/717.feature
- Makefile
- api/v1alpha1/repo_manager_types.go
- bundle/manifests/pulp-operator.clusterserviceversion.yaml
- bundle/manifests/repo-manager.pulpproject.org_pulps.yaml
- config/manager/manager.yaml
- config/manifests/bases/pulp-operator.clusterserviceversion.yaml
- config/samples/galaxy.azure.ci.yaml
- config/samples/galaxy.s3.ci.yaml
- config/samples/galaxy.yaml
- config/samples/pulpproject_v1beta1_pulp_cr.galaxy.ocp.ci.yaml
- config/samples/simple-external-cache.yaml
- config/samples/simple-external-db.yaml
- config/samples/simple-sso.yaml
- config/samples/simple.ingress.yaml
- config/samples/simple.yaml
- controllers/repo_manager/api.go
- controllers/repo_manager/content.go
- controllers/repo_manager/controller_test.go
- controllers/repo_manager/worker.go
`galaxy-minimal` images.
Also have CI test the new big s6-contining images
`pulp` and `pulp-galaxy-ng`.
Also, the unstable images are now called "nightly" rather
than "latest".
(There are no unstable images for `pulp-galaxy-ng`).
closes: #717
> Utilize the renamed `pulp-minimal` and

- .github/workflows/ci.yml
- .github/workflows/pr.yml
- CHANGES/717.feature
- bundle/manifests/pulp-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- config/manifests/bases/pulp-operator.clusterserviceversion.yaml
- config/samples/pulpproject_v1beta1_pulp_cr.ci.yaml
- config/samples/pulpproject_v1beta1_pulp_cr.galaxy.azure.ci.yaml
- config/samples/pulpproject_v1beta1_pulp_cr.galaxy.ci.yaml
- config/samples/pulpproject_v1beta1_pulp_cr.galaxy.ocp.ci.yaml
- config/samples/pulpproject_v1beta1_pulp_cr.galaxy.s3.ci.yaml
- config/samples/pulpproject_v1beta1_pulp_cr.galaxy.s6.ci.yaml
- config/samples/pulpproject_v1beta1_pulp_cr.molecule.ci.yaml
- config/samples/pulpproject_v1beta1_pulp_cr.pulp-demo.yaml
- config/samples/pulpproject_v1beta1_pulp_cr.s6.ci.yaml
- docs/container.md
- up.sh
`galaxy-minimal` images.
Also have CI test the new big s6-contining images
`pulp` and `pulp-galaxy-ng`.
Also, the unstable images are now called "nightly" rather than "latest".
(There are no unstable images for `pulp-galaxy-ng`).
closes: #717
> ansible: Utilize the renamed pulp-minimal and

- api/v1alpha1/repo_manager_types.go
- config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
- controllers/repo_manager/README.md
- controllers/repo_manager/controller.go
Setting the operator as unmanaged will allow to "disable" the operator without having to delete the controller-manager pod. It can be useful in situations where we need to test something and don't want the operator to reconcile our changes.
[noissue]
> Add a field to set operator unmanaged

- config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
- controllers/repo_manager/README.md
- controllers/repo_manager/controller.go
- controllers/repo_manager/redis.go
This commit adds the logic of removing Redis resource based on Pulp CR modification. For example, if .cache.enabled was true and now we set it to false, all cache resources will be removed. 
[noissue]
> Remove cache resources with CR update

- CHANGES/737.bugfix
- controllers/repo_manager/api.go
- controllers/repo_manager/content.go
When the service was configured as "headless", the nginx upstream configuration was pointing directly to the pods backing it. Because of that, when an endpoint died, the nginx was still pointing to the same address which was returning errors.
fixes #737
> Modify api and content svc to get clusterip

- .ci/scripts/backup_and_restore.sh
- CHANGES/735.bugfix
- CHANGES/736.bugfix
- controllers/repo_manager/controller.go
- controllers/repo_manager/controller_test.go
- controllers/repo_manager/route.go
- controllers/repo_manager/status.go
- controllers/repo_manager/utils.go
refactored pulpStatus
fixes #735
fixes #736
also "fixed" an issue in which r.Status().Update() triggers a reconcile (resulting in RequeueAfter to not work if pulpStatus is modified), stopping with the spam of "pulp <resource> not ready yet ..." in logs.
> Fix some issues with pulp status

- CHANGES/751.bugfix
- controllers/repo_manager/status.go
If more than one operator worker try to update a k8s resource it is common to receive an error like:
```
"error": "Operation cannot be fulfilled on galaxies.repo-manager.ansible.com
\"galaxy-example\": the object has been modified; please apply your changes
to the latest version and try again"
```
This commit is returning an error (which will trigger a reconcile loop) in case it failed to update the `.status.conditions[]` field.
fixes #751
> Adding a "retry" in case it fails to update status

- .github/workflows/ci.yml
- Makefile
This modifies the CI to use multi-architecture builds. A fix for using buildx instead of build is provided (a context argument is needed here). I'm specifically submitting that as we would like to use that operator and we have a multi-arch amd64/arm64 cluster, where workloads are usually failing when they don't provide multi-arch containers.
[Here](https://github.com/StopMotionCuber/pulp-operator/actions/runs/3428729319/jobs/5713398320) you can see a sample workflow run, using a modified branch for rapid testing and removed dependent steps. Obviously the push didn't succeed, as I do not have quay.io credentials.
I didn't create an issue for this PR. In case something like that is needed for the changelog, let me know
> Enable multi-architecture builds from CI

- CHANGES/550.feature
- controllers/restore/controller.go
- controllers/restore/utils.go
If lock configmap is found it means that the restore already ran, so the controller should stop execution.
To rerun a restore the user will have to manually delete the lock configmap first.
closes #550
> Added a control CM to avoid restore reconcile run

- bundle/manifests/pulp-operator.clusterserviceversion.yaml
Adding the full path to redis and postgres image containers in the CSV.
[noissue]
Signed-off-by: Leo Ochoa [lochoa@redhat.com](mailto:lochoa@redhat.com)
> Add missing full path to container images

- controllers/repo_manager/worker.go
> Adding default readinessProbe for worker

- controllers/repo_manager/api.go
- controllers/repo_manager/content.go
- controllers/repo_manager/ingress.go
- controllers/repo_manager/redis.go
- controllers/repo_manager/route.go
- controllers/repo_manager/utils.go
- controllers/repo_manager/web.go
- controllers/repo_manager/worker.go
updateObject is used by reconcileObject and reconcileMetadata. It will use the "modified" function provided to check if a field/spec has been modified and will run an "update" request to the object if needed.
[noissue]
> Add updateObject function

- roles/pulp-api/tasks/main.yml
The `secret_key` fact isn't use at all by the operator.
[noissue]
> pulp-api: remove secret_key fact

- roles/pulp-routes/tasks/main.yml
When upgrading from an older operator release (when OCP route was still using the pulp-web pod) then the pulp-web deployment is still present after the upgrade.
This ensures that the pulp web deployment is absent when the ingress type is configured to use OCP route.
[noissue]
> Remove pulp-web on upgrade with OCP route

- bundle/manifests/pulp-operator.clusterserviceversion.yaml
- config/rbac/cluster_role.yaml
- config/rbac/cluster_role_binding.yaml
- config/rbac/kustomization.yaml
- config/rbac/role.yaml
- molecule/default/resources.yml
This change was initially made to enable downstream builds.  We have since added logic downstream to handle this, and this change can be reverted.
> Revert "config/rbac: Add ingresses.config.openshift.io"

- CHANGES/675.bugfix
- controllers/repo_manager/controller.go
From pulpcore doc https://docs.pulpproject.org/pulpcore/configuration/settings.html#content-origin this is a required setting, so the operator will output an error if ingress_host is not provided.
closes #675
> Add check for nil ingress_host

- controllers/repo_manager/controller.go
Some errors, like a missing/wrong configuration will never be fixed by triggering a reconciliation. For such errors, the controller will keep spamming error messages (with an exponential backoff retry) until the problem is fixed, which is also consuming resources without need. This commit is removing the reconciliation request for some errors that would not be fixed by retriggering the reconcile method. ref: #822
[noissue]
> Remove reconcile trigger for some specific errors

- CHANGES/827.doc
- docs/install/install.md
- mkdocs.yml
The current version of the operator is already allowing multiple instances of Pulp. This commit is only documenting the steps to do so and also how to install it as non-clusteradmin. closes #827
> Doc install as regular user and multiple instances

- api/v1alpha1/repo_manager_types.go
- config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
- controllers/repo_manager/README.md
- controllers/repo_manager/api.go
- controllers/repo_manager/content.go
- controllers/repo_manager/controller.go
- controllers/repo_manager/utils.go
- controllers/utils.go
- go.mod
- go.sum
The ansibleMigrationTasks method will automate some steps needed when upgrading from ansible-based to go-based version of the operator.
[noissue]
> Add ansibleMigrationTasks method

- .ci/scripts/pulp_tests.sh
- controllers/repo_manager/database.go
Golang version is keeping the database service deployed by ansible to avoid having to touch the secrets (which could have been manually modified by users). In this case, we need to also watch for any modification in this service with the golang controller because if users modify or delete it they will be lost on how to proceed and pulp-api pods would lose access to the database.
[noissue]
> Add reconciliation for old postgres svc

- .ci/scripts/galaxy_ng-tests.sh
- .ci/scripts/pulp_tests.sh
- .github/workflows/ci.yml
- .github/workflows/pr.yml
- bundle/manifests/pulp.pulpproject.org_pulps.yaml
- config/crd/bases/pulpproject_v1beta1_pulp_crd.yaml
- roles/backup/tasks/update_status.yml
- roles/postgres/tasks/main.yml
- roles/postgres/tasks/migrate_data.yml
- roles/postgres/tasks/upgrade_postgres.yml
- roles/pulp-api/tasks/admin_password_configuration.yml
- roles/pulp-api/tasks/azure-storage-configuration.yml
- roles/pulp-api/tasks/container_auth_configuration.yml
- roles/pulp-api/tasks/db_fields_encryption_configuration.yml
- roles/pulp-api/tasks/get_node_ip.yml
- roles/pulp-api/tasks/main.yml
- roles/pulp-api/tasks/s3-storage-configuration.yml
- roles/pulp-api/tasks/signing_service.yml
- roles/pulp-api/tasks/sso-configuration.yml
- roles/pulp-content/tasks/main.yml
- roles/pulp-resource-manager/tasks/main.yml
- roles/pulp-routes/tasks/main.yml
- roles/pulp-status/tasks/main.yml
- roles/pulp-web/tasks/main.yml
- roles/pulp-worker/tasks/main.yml
- roles/restore/tasks/update_status.yml
Modify the .status.conditions.lastTransitionTime to be compatible with k8s apimachinery format (used in golang version) and add a .status.conditions.message field (which was missing because we were already setting the messages in the tasks).
[noissue]
> Modify lastTransitionTime and add message field

- .ci/prow/openshift-test.sh
We are installing the operator using OLM (bundle installation) therefore we don't need the `make deploy` anymore.
> Remove the `make deploy` from prow script

- roles/common/tasks/create_app_sa.yml
- roles/common/tasks/main.yml
There is no longer a reason to patch the operator SA now that we added an application specific ServiceAccount.
> Remove update task for operator SA

- CHANGES/882.doc
- controllers/repo_manager/api.go
- docs/configuring/storage.md
On the one hand this fixes that no `s3-region` needs to be specified in the secret, if the `s3-endpoint` is already given (this is ignored by `django-storages` anyways, as the custom endpoint overrides the region).
On the other hand the possibility to specify the `s3-endpoint` is documented
Closes #882
> Improvements for custom S3 endpoints

- roles/backup/tasks/postgres.yml
Change date format to avoid : character. Some filesystems do not allow for this.
Fixes: https://issues.redhat.com/browse/AAP-9250
> change date format to avoid ':'

- roles/pulp-api/tasks/get_node_ip.yml
By overriding the galaxy_feature_flags configuration for enabling the EE then we loose all other default values from galaxy_feature_flags. Prior pulpcore 3.23 this wasn't a problem but starting 3.23, if the galaxy_feature_flags dict doesn't have some required key then dynaconf will fail (like during the database migration).
```console
+ /usr/bin/pulpcore-manager migrate --noinput Traceback (most recent call last):
Traceback (most recent call last):
File "/usr/bin/pulpcore-manager", line 33, in <module>
sys.exit(load_entry_point('pulpcore==3.23.2', 'console_scripts', 'pulpcore-manager')())
File "/usr/lib/python3.9/site-packages/pulpcore/app/manage.py", line 11, in manage
execute_from_command_line(sys.argv)
File "/usr/lib/python3.9/site-packages/django/core/management/__init__.py", line …
```
> [ansible] api: fix galaxy_feature_flags configuration

- bundle/manifests/pulp-operator.clusterserviceversion.yaml
- config/manifests/bases/pulp-operator.clusterserviceversion.yaml
When using the UI, there's only the ReadWriteMany value available for the file_storage_access_mode parameter.
ReadWriteOnce is also an available option.
https://github.com/pulp/pulp-operator/blob/ansible/config/crd/bases/pulpproject_v1beta1_pulp_crd.yaml#L159-L165
[noissue]
> [ansible] csv: Fix file_storage_access_mode enum

- bundle/manifests/pulp-operator.clusterserviceversion.yaml
- config/rbac/cluster_role.yaml
This previous commit was not a clean revert, and missed two rules that are needed (list and watch) on the ingresses resource for the operator SA.  
* https://github.com/pulp/pulp-operator/commit/47d4ba6083094d4acacf88d76bda3a151b423e7d
> Add back list & watch rules for cluster-wide ingresses

- bundle/manifests/pulp-operator.clusterserviceversion.yaml
- config/rbac/cluster_role.yaml
When using resourceNames on the config.openshift.io apigroup for querying the ingresses resource then we don't need to specify the resourceNames.
Using it will generate a permission error during the operator execution but won't cause the deployment to fail.
```console
[E0526 01:41:41.701732 7 reflector.go:138] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:245: Failed to watch config.openshift.io/v1, Kind=Ingress: failed to list config.openshift.io/v1, Kind=Ingress: ingresses.config.openshift.io is forbidden: User "system:serviceaccount:aap:automation-hub-operator-sa" cannot list resource "ingresses" in API group "config.openshift.io" at the cluster scope
```
[noissue]
> [ansible] rbac: remove resourceNames for OCP ingresses

- .ci/scripts/kubelinter.sh
- .github/workflows/ci.yml
- .gitleaks.toml
- apis/repo-manager.pulpproject.org/v1beta2/pulp_backup_types.go
- bundle/manifests/repo-manager.pulpproject.org_pulpbackups.yaml
- config/crd/bases/repo-manager.pulpproject.org_pulpbackups.yaml
- controllers/backup/controller.go
- controllers/backup/cr.go
- controllers/backup/database.go
- controllers/backup/pulp_dir.go
- controllers/backup/secret.go
- controllers/backup/utils.go
- controllers/restore/controller.go
- controllers/restore/database.go
- controllers/restore/deploy.go
- controllers/restore/pulp_dir.go
- controllers/restore/secret.go
- controllers/restore/utils.go
This commit configures the backup and restore controllers to allow
compatibility with ansible version of the operator.
ref: https://issues.redhat.com/browse/AAP-8757
ref: https://github.com/pulp/pulp-operator/issues/693
[noissue]
> Modify bkp/restore controllers for compatibility

- bundle/manifests/pulp.pulpproject.org_pulps.yaml
- config/crd/bases/pulpproject_v1beta1_pulp_crd.yaml
The execution_environments feature flag should be a boolean, not a string type in the CRD schema.
> Feature flag should be boolean, not string type

- apis/repo-manager.pulpproject.org/v1beta2/pulp_types.go
- bundle/manifests/repo-manager.pulpproject.org_pulps.yaml
- config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
- controllers/repo_manager/README.md
- controllers/repo_manager/controller.go
This commit adds a field in CRD to allow bypassing the verification of `image_version` being different than `image_web_version`. It can be useful in situations like testing news configs without re-building both images with the same tag.
[noissue]
> Add a field to suppress the check of image_version

- CHANGES/969.feature
- controllers/repo_manager/content.go
- controllers/utils.go
> Add a wait for API pods when image version changed

- main.go
Providing the current version in logs can be helpful during troubleshooting. For example, when an issue already fixed in version X is found in the running operator this is probably because the version deployed is older than the one with the fix. [noissue]
> Add a log message with current version

- CHANGES/987.bugfix
- controllers/repo_manager/api.go
- controllers/repo_manager/utils.go
- main.go
Modify the readiness probe endpoint for content pods when DOMAIN is enabled and update the "true"/"false" strings to boolean in settings.py (pulp-server secret).
fixes: #987
> Update content probe and settings.py bool values

- .ci/assets/kubernetes/signing_scripts.configmap.yaml
- CHANGES/994.bugfix
This commit updates the script so that it will not ask for the passphrase key protection and instead use the supplied one in batch mode.
fixes: #994
> Update signing scripts to work with passphrase

- bundle/manifests/pulp-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- config/manifests/bases/pulp-operator.clusterserviceversion.yaml
- roles/pulp-api/tasks/signing_service.yml
Follow-up for https://github.com/pulp/pulp-operator/pull/1002
This PR does the following:
* Adds the GPG init container RELATED_IMAGE_ ref everywhere needed (CSV & manager deployment)
* Renames it from `RELATED_IMAGE_GPG_INIT_CONTAINER` to `RELATED_IMAGE_PULP_INIT_GPG_CONTAINER` for consistency with other projects.
> Rename RELATED_IMAGE_ for GPG init container

- .ci/scripts/pulp_tests.sh
- .github/workflows/ci.yml
The `port-forward` command does not have a retry in case of pod failure. Because of that, sometimes the CI was failing like: _"an error occurred forwarding 24817 -> 24817: error forwarding port 24817 to pod <pod id>, uid : Error response from daemon: No such container"_ 
this commit updates the test script replacing the `port-forwarding` with the service `nodeport` which is also helpful to validate the `nodeport` configuration
[noissue]
> Use nodeport instead of port-forward in tests

- config/samples/pulpproject_v1beta1_pulp_cr.galaxy.ocp.ci.yaml
- config/samples/pulpproject_v1beta1_pulp_cr.ocp.ci.yaml
Remove the file_storage_* configs because there is no storage class defined in the samples.
[noissue]
> Update OCP pipeline sample CRs

- CHANGES/1098.bugfix
- controllers/backup/secret.go
- controllers/restore/secret.go
- main.go
Instead of using the `createBackupFile` method (that stores the Secret data in plain text) using the `createSecretBackupFile` method (which stores the entire Secret object in YAML format and without decoding it) fixed the issue with the special chars.
fixes: #1098
> Fix bkp issue in pulp-secret-key and special chars

- .ci/scripts/backup_and_restore.sh
- controllers/deployment.go
- controllers/ingress.go
- controllers/ocp/route.go
- controllers/ocp/utils.go
- controllers/repo_manager/api.go
- controllers/repo_manager/content.go
- controllers/repo_manager/controller.go
- controllers/repo_manager/controller_test.go
- controllers/repo_manager/database.go
- controllers/repo_manager/ingress.go
- controllers/repo_manager/job.go
- controllers/repo_manager/pdb.go
- controllers/repo_manager/redis.go
- controllers/repo_manager/secret.go
- controllers/repo_manager/utils.go
- controllers/repo_manager/web.go
- controllers/settings/labels.go
- controllers/telemetry.go
- main.go
:warning: THIS IS A BREAKING CHANGE! :warning:
This PR centralizes the definition of the labels used by Pulp resources. The operator can get into
an errored state trying to update some resources but failing to do so because `Selector` is an
immutable field.
To workaround this issue:
* make sure to have a backup of all pulp components (pvc, secrets, pulp cr, etc), especially database
* make sure there is no pending task:
```
2023-09-15T15:08:23Z    INFO    repo_manager/controller.go:235  Operator tasks synced
```
* reprovision the sts and deployments
```
oc delete sts pulp-database
oc delete deployment pulp-web pulp-redis
```
> Centralize labels definition in settings package

- .github/workflows/ci.yml
- CHANGES/1100.misc
- config/samples/simple-test.yaml
- config/samples/simple-with-reduced-migration-cpu.yaml
The two-deployments job tests that 2 deployments of Pulp in one namespace are able to start succesfully. No tests are run after the operator reports that the deployments are up.
closes: #1100
> Adds two-deployments job to GHA

- controllers/repo_manager/secret.go
This should resolve the immediate problems with #1132
The missing 'ai_deny_index' sub key is added, and the the key = value is all one line. This PR does not solve how pulp_settings replaces existing keys in settings.py that have multi-line values.
> Update GALAXY_FEATURE_FLAGS in controllers/repo_manager/secret.go

- .ci/scripts/ldap_config.sh
- .ci/scripts/ldap_test.sh
- .github/workflows/ci.yml
- CHANGES/1124.misc
- config/samples/ldap.yaml
> Add a pipeline job to test LDAP integration

- controllers/telemetry.go
Fix a regression added in
https://github.com/pulp/pulp-operator/pull/1109/files#diff-83f59b06f166f6814a7451c68f2786eca1db98bbdc8bbe2a3fd3198e6a46b2f0L194-L196 [noissue]
> Add "otel" label back to telemetry Service

- apis/repo-manager.pulpproject.org/v1beta2/pulp_types.go
- bundle/manifests/pulp-operator.clusterserviceversion.yaml
- bundle/manifests/repo-manager.pulpproject.org_pulps.yaml
- config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
- controllers/repo_manager/README.md
- controllers/repo_manager/controller.go
- controllers/repo_manager/redis.go
This field will be helpful to avoid running the cache deprovisioning task in every reconciliation loop.
[noissue]
> Add a .status.managed_cache_enabled field

- .github/workflows/ci.yml
- .github/workflows/k8s_versions.yml
Node.js 16 actions are deprecated. This commit updates go, python, and checkout actions to use Node.js 20.
[noissue]
> Update github actions to use node.js 20

- config/samples/simple-external-cache.yaml
- config/samples/simple-sso.yaml
- config/samples/simple-test.yaml
- config/samples/simple-with-reduced-migration-cpu.yaml
- config/samples/simple.ingress.yaml
- config/samples/simple.yaml
Our pipeline was failing for tests with nightly image, but was running fine for tests using stable. API logs:
```
2024-04-12T18:00:24.335914694Z pulp [e336954360eb4dd7907c1885ece3aca6]: django.request:ERROR: Internal Server Error: /v2/test/fixture/blobs/uploads/
2024-04-12T18:00:24.335953256Z Traceback (most recent call last):
2024-04-12T18:00:24.335959187Z   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
2024-04-12T18:00:24.335965158Z     response = get_response(request)
...
2024-04-12T18:00:24.336152879Z     raise LookupError("Could not determine ViewSet base name for model {}".format(model_class))
2024-04-12T18:00:24.336158811Z LookupError: Could not determine ViewSet base name for model <class 'pulp_container.app.models.Upload'>
``` …
> Update samples with stable image tag

- CHANGES/1247.bugfix
- controllers/repo_manager/precheck.go
> Add file_storage_storage_class dependencies check

- CHANGES.md
- CHANGES/.TEMPLATE.md
- CHANGES/1284.misc
- pyproject.toml
Having each release entry as an H1 header prevented mkdocs from rendering the right sidebar ToC.
This uses the same `.TEMPLATE` as plugin_template.
Closes: #1284
> Fix changelog title hierarchy

- CHANGES/1271.bugfix
- apis/repo-manager.pulpproject.org/v1beta2/pulp_types.go
- bundle/manifests/pulp-operator.clusterserviceversion.yaml
- bundle/manifests/repo-manager.pulpproject.org_pulps.yaml
- config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
- config/manifests/bases/pulp-operator.clusterserviceversion.yaml
- controllers/deployment.go
- controllers/ocp/route.go
- controllers/repo_manager/README.md
- controllers/repo_manager/controller.go
- controllers/repo_manager/ingress.go
- controllers/repo_manager/secret.go
- controllers/repo_manager/utils.go
- controllers/repo_manager/web.go
- controllers/utils.go
- main.go
- staging_docs/admin/guides/configurations/database.md
- staging_docs/admin/guides/configurations/pulp_settings.md
Instead of providing custom configurations through the `pulp_settings` RawExtension field, this commit adds a new field called `custom_pulp_settings` which receives the name of a ConfigMap (that users should create manually) with the custom configurations.
closes: #1271
> Modified the way to provide custom Pulp settings

- staging_docs/user/guides/common_issues.md
> Add docs to manually run migrations

- roles/postgres/tasks/main.yml
- roles/postgres/tasks/upgrade_postgres.yml
- roles/postgres/templates/postgres.yaml.j2
- roles/pulp-api/templates/pulp-api.deployment.yaml.j2
- roles/pulp-content/templates/pulp-content.deployment.yaml.j2
- roles/pulp-status/tasks/main.yml
- roles/pulp-web/templates/pulp-web.deployment.yaml.j2
- roles/pulp-worker/templates/pulp-worker.deployment.yaml.j2
- roles/redis/templates/redis.deployment.yaml.j2
Change apiVersion to avoid failure while deploying hub
Resolves:
https://issues.redhat.com/browse/AAP-28261
Mirrors:
https://github.com/ansible/galaxy-operator/pull/129/commits/4b526eb82d94695194fb910dc77db39e567b6bc2
> Change apiVersion to avoid failure while deploying hub

- CHANGES/1327.bugfix
- controllers/repo_manager/secret.go
Enable access via IAM Role Service Accounts for S3 backends by making the attributes s3-access-key-id and s3-secret-access-key optional in object_storage_s3_secret
closes #1327
> Enable IRSA for aws s3 backends

- CHANGES/1346.feature
- controllers/deployment.go
- controllers/repo_manager/job.go
- controllers/settings/jobs.go
- controllers/utils.go
- docs/configuring/metadata_signing.md
- main.go
> Add support to apt signing service

- .ci/scripts/telemetry.sh
- .github/workflows/ci.yml
- .github/workflows/k8s_versions.yml
- CHANGES/1361.bugfix
- controllers/telemetry.go
- main.go
> Update otel entrypoint from api container

- .github/workflows/ci.yml
- .github/workflows/k8s_versions.yml
- config/samples/k8s_versions_ci.yaml
- config/samples/ldap.yaml
- config/samples/simple-external-db.yaml
- config/samples/simple-test.yaml
- config/samples/simple-with-reduced-migration-cpu.yaml
- config/samples/simple.ingress.yaml
- config/samples/simple.yaml
- config/samples/telemetry.yaml
pulp-oci-image repo has been updated and we are currently missing the amd64 architecture for pulp-web image in Quay. As a workaround, this commit pins to an older image that still supports amd64. [noissue]
> Temporarily pin the pulp-web version in CI samples

- config/samples/pulpproject_v1beta1_pulp_cr.galaxy.ocp.ci.yaml
This commit modifies the DB StorageClass to workaround an issue in prow pipeline and postgres pods crashing because of a permission error:
```
chmod: changing permissions of '/var/lib/postgresql/data/pgdata': Operation not permitted
```
[noissue]
> Modify galaxy ocp sample DB StorageClass

- CHANGES/1401.feature
- controllers/deployment.go
- controllers/repo_manager/job.go
- controllers/settings/jobs.go
- controllers/utils.go
- docs/configuring/metadata_signing.md
closes: #1401
This PR enables supporting RPM signing service.
The signing script name should be `rpm_script.sh` inside the secret `signing-scripts`. Includes a working example.
As with other signing service types, the signing secret should already be in place.
> Add support to RPM signing service

- controllers/repo_manager/secret.go
- controllers/utils.go
- main.go
This commit fixes an issue with `ingress.spec.rules.http.paths.path` not being updated after changing `CONTENT_ORIGIN_PATH` or `API_ROOT` in the `custom_pulp_setting` ConfigMap.
[noissue]
> Fix an issue with wrong route/ingress paths

- CHANGES/1411.bugfix
- controllers/repo_manager/secret.go
We don't need to set a default value for `API_ROOT` in the operator because it is already defined in pulpcore:
https://github.com/pulp/pulpcore/blob/61ac2b622eeaff7f3fde0cbe40d2e9919d43ebbc/pulpcore/app/settings.py#L100
note: this commit will **not** handle a possible issue with duplicate value for the other default configs.
fixes: #1411
> Remove the `API_ROOT` from default settings

- controllers/repo_manager/sso.go
The sso_secret option in the Pulp CR is not enumerated correctly. It uses a standard 'for key := range x' which will always be in a random order in Golang. This causes the operator to continuously think the secret data changed and reconcile the resources in an infinite loop.
This PR addresses this by ensuring they are always enumerated in the same order.
Fixes #1395
> Fix sso_secret key enumeration

- .ci/prow/Dockerfile.ci-operator
The tests in prow are failing to run:
```
ERRO[2025-04-24T16:42:00Z] 
* could not run steps: step deploy-pulp-on-openshift failed: "deploy-pulp-on-openshift" test steps failed: "deploy-pulp-on-openshift" pod "deploy-pulp-on-openshift-deploy-pulp" failed: could not watch pod: the pod ci-op-lkxb6fk0/deploy-pulp-on-openshift-deploy-pulp failed after 37s (failed containers: test): ContainerFailed one or more containers exited
Container test exited with code 1, reason Error
---
oc: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by oc)
oc: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by oc)
oc: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by oc)
{"component":"entrypoint","error":"wrapped process failed: exit status …
```
> Change the link to download oc (used in prow test)

- config/samples/simple-ocp.yaml
prow tests were failing with:
```
persistentvolumeclaim/example-pulp-postgres-example-pulp-database-0   storageclass.storage.k8s.io "gp3-csi" not found
persistentvolumeclaim/example-pulp-file-storage                       storageclass.storage.k8s.io "gp3-csi" not found
```
[noissue]
> Modify the SC definition in simple-ocp sample

- controllers/repo_manager/secret.go
By default, it is already defined as `True` (and ignored for local file storage). Removing it to avoid conflicts when it is also defined in `custom_pulp_settings`.
ref: https://github.com/pulp/pulpcore/issues/6761
[noissue]
> Remove `REDIRECT_TO_OBJECT_STORAGE` definition

- controllers/repo_manager/secret.go
- docs/admin/guides/configurations/pulp_settings.md
This PR adds configurable S3 addressing style support to the Pulp operator, allowing users to specify whether to use "path" or "virtual" addressing style for S3-compatible storage services.
Currently, the S3 addressing style is hardcoded to "path" in the operator code (line 429 in `secret.go`), which causes issues with S3-compatible services like Tencent COS that require "virtual" addressing style. This results in `PathStyleDomainForbidden` errors when trying to use these services.
- Add `s3-addressing-style` key support in S3 secret retrieval
- Make `addressing_style` configurable instead of hardcoded "path"
- Add `getAddressingStyle` helper function with "path" as default
- Support both "path" and "virtual" addressing styles
- Maintain backward compatibility
- …
> feat: add configurable S3 addressing style support
