pulp/pulp-operator

README.md, deploy/crds/pulpproject_v1alpha1_pulp_cr.yaml, deploy/operator.yaml, molecule/test-cluster/playbook.yml, molecule/test-local/playbook.yml, playbook.yml, roles/pulp-content/defaults/main.yml, roles/redis/templates/redis.deployment.yaml
Multiple fixes and improvements from:
https://etherpad.net/p/Pulp_K8s_Operator_TODO
=> Short term todo 2

deploy/operator.yaml, playbook.yml, roles/pulp-api/tasks/main.yml, roles/pulp-api/templates/pulp-api.deployment.yaml, roles/pulp-content/tasks/main.yml, roles/pulp-content/templates/pulp-content.deployment.yaml, roles/pulp-resource-manager/templates/pulp-resource-manager.deployment.yaml, roles/pulp-worker/templates/pulp-worker.deployment.yaml
Collapse 4 container images into 1.
Use commands to differentiate the 4+ containers.
Accomodates task #5060 (https://github.com/pulp/pulpcore/pull/203)
Also, make the image name a variable in playbook.yml
=> Collapse 4 container images into 1.

.travis.yml, .travis/quay-push.sh
initial part of implementing:
re: 5062
https://pulp.plan.io/issues/5062
Create pulpcore and pulp_file container images automatically via CI
=> Upload master branch images to quay with the latest tag

.travis/pulp-operator-check-and-wait.sh
Solution: Wait for them; do not assume they are up when the status page comes up.
=>     Problem: pulp-operator-check-and-wait.sh does not wait for content app or workers to come up

.travis/pulp-operator-check-and-wait.sh
=> pulp-operator-check-and-wait.sh: handle httpie getting HTTP 104

.travis/pulp_file-tests.sh, deploy/crds/pulpproject_v1alpha1_pulp_cr.default.yaml, deploy/crds/pulpproject_v1alpha1_pulp_cr.travis.yaml, playbook.yml, roles/pulp-api/tasks/main.yml, roles/pulp-api/templates/pulp-server.config-map.yaml
re: #5435
https://pulp.plan.io/issues/5435
=> Allows user to specify all pulp_settings

COPYRIGHT, LICENSE
https://pulp.plan.io/issues/4592
closes #4592
=> Adding LICENSE and COPYRIGHT

.travis.yml
fix broken builds:
https://travis-ci.com/pulp/pulp-operator/jobs/274706706#L1954
=> Change httpie

.travis/pulp-operator-check-and-wait.sh
https://pulp.plan.io/issues/5763
closes #5763
=> Refactoring pulp-operator-check-and-wait.sh

roles/pulp-api/defaults/main.yml, roles/pulp-api/tasks/main.yml
https://pulp.plan.io/issues/5962
closes #5962
=> Workaround for pulp_settings

README.md, docs/doc_requirements.txt, docs/index.md, docs/quickstart.md, mkdocs.yml
=> Introducing mkdocs

.travis/validate_commit_message.py, CHANGES/.TEMPLATE.md, docs/CHANGES.md, mkdocs.yml, pyproject.toml
=> Introducing towncrier

.travis/quay-push.sh
pulp-operator was pushed 3 times:
https://travis-ci.com/github/pulp/pulp-operator/jobs/357081217
=> Fix quay push

insta-demo/pulp-insta-demo.sh
=> Removing insta-demo workaround

README.md, docs/contributing.md, docs/roles/postgres.md, docs/roles/pulp-api.md, docs/roles/pulp-content.md, docs/roles/pulp-resource-manager.md, docs/roles/pulp-routes.md, docs/roles/pulp-worker.md, docs/roles/redis.md, mkdocs.yml, roles/postgres/README.md, roles/postgres/meta/main.yml, roles/pulp-api/README.md, roles/pulp-api/meta/main.yml, roles/pulp-content/README.md, roles/pulp-content/meta/main.yml, roles/pulp-resource-manager/README.md, roles/pulp-resource-manager/meta/main.yml, roles/pulp-routes/README.md, roles/pulp-routes/meta/main.yml, roles/pulp-worker/README.md, roles/pulp-worker/meta/main.yml, roles/redis/README.md, roles/redis/meta/main.yml
=> Adding docs for roles

docs/contributing.md, molecule/cluster/molecule.yml, molecule/default/molecule.yml, molecule/test-local/molecule.yml
- Correct contributing docs
- Profile molecule tasks
[noissue]
=> Minor improvements

.travis/before_install.sh, .travis/deploy.sh, CHANGES/7171.feature, containers/README.md, containers/ansible.cfg, containers/build.yaml, containers/common_tasks.yaml, containers/images/pulp/Dockerfile.j2, containers/images/pulp/container-assets/pulp-api, containers/images/pulp/container-assets/pulp-common-entrypoint.sh, containers/images/pulp/container-assets/pulp-content, containers/images/pulp/container-assets/pulp-resource-manager, containers/images/pulp/container-assets/pulp-worker, containers/images/pulp/container-assets/wait_on_database_migrations.sh, containers/images/pulp/container-assets/wait_on_postgres.py, containers/push.yaml, containers/vars/defaults.yaml, docs/containers.md, mkdocs.yml
https://pulp.plan.io/issues/7171
closes #7171
Related PR: https://github.com/pulp/pulpcore/pull/800
=> Moving containers from pulpcore to pulp-operator

.travis.yml
=> Install molecule-docker

.travis.yml, molecule/default/molecule.yml
=> Replace operator image

.travis/molecule.sh, molecule/default/destroy.yml, molecule/default/prepare.yml, molecule/kind/destroy.yml
Fix: https://travis-ci.com/github/pulp/pulp-operator/jobs/421484244#L632
=> Expose kustomize version and fix molecule tests

containers/images/pulp/Dockerfile.j2, roles/postgres/meta/main.yml, roles/pulp-api/meta/main.yml, roles/pulp-content/meta/main.yml, roles/pulp-resource-manager/meta/main.yml, roles/pulp-routes/meta/main.yml, roles/pulp-worker/meta/main.yml, roles/redis/meta/main.yml
=> Upgrade to fedora 33

.ci/scripts/deploy.sh, Makefile, bundle.Dockerfile, bundle/manifests/pulp-operator-controller-manager-metrics-service_v1_service.yaml, bundle/manifests/pulp-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/manifests/pulp.pulpproject.org_pulps.yaml, bundle/metadata/annotations.yaml, bundle/tests/scorecard/config.yaml, config/manager/kustomization.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, config/manifests/kustomization.yaml, config/samples/kustomization.yaml
=> Deploying pulp bundle

.github/workflows/ci.yml
sudo makes it use the wrong pip
=> Deploy without sudo

.ci/scripts/deploy.sh, .ci/scripts/pulp-operator-check-and-wait.sh, .ci/scripts/pulp_file-tests.sh, .github/workflows/ci.yml, .github/workflows/pr.yml, .gitignore, CHANGES/5657.feature, containers/build.yaml, containers/images/pulp/Containerfile.core.j2, containers/images/pulp/Containerfile.web.j2, containers/images/pulp/container-assets/nginx, containers/images/pulp/container-assets/nginx-check, containers/images/pulp/container-assets/nginx.conf, containers/images/pulp/container-assets/pulp-common-entrypoint.sh, containers/vars/defaults.yaml, docs/roles/pulp-web.md, insta-demo/pulp-insta-demo.sh, mkdocs.yml, playbook.yml, roles/pulp-content/templates/pulp-content.service.yaml.j2, roles/pulp-routes/templates/pulp-api.route.yaml.j2, roles/pulp-routes/templates/pulp-content.route.yaml.j2, roles/pulp-web/README.md, roles/pulp-web/defaults/main.yml, roles/pulp-web/meta/main.yml, roles/pulp-web/tasks/main.yml, roles/pulp-web/templates/pulp-web.deployment.yaml.j2, roles/pulp-web/templates/pulp-web.service.yaml.j2
* Build pulpweb container.
* Add role for pulp-web deployment.
* Switch CI to use minikube and build image in minikube registry
fixes #5657
https://pulp.plan.io/issues/5657
=> Add deployment of nginx webserver with pulp snippets

.github/workflows/ci.yml
it is failing on `main`: https://github.com/pulp/pulp-operator/runs/2007986791?check_suite_focus=true
=> Fix CI jobs

.ci/scripts/molecule.sh, CHANGES/8293.misc, README.md, deploy/crds/pulpproject_v1beta1_pulp_cr.ci.yaml, deploy/crds/pulpproject_v1beta1_pulp_cr.default.yaml, deploy/crds/pulpproject_v1beta1_pulp_cr.pulp-demo.yaml, deploy/crds/pulpproject_v1beta1_pulp_crd.yaml, down.sh, molecule/default/converge.yml, molecule/default/destroy.yml, molecule/default/tasks/pulp_test.yml, molecule/kind/molecule.yml, up.sh, watches.yaml
* Update references to custom resource version
closes #8293
https://pulp.plan.io/issues/8293
=> Update custom resource definition to v1beta1

.ci/ansible/vars.yaml, .ci/scripts/deploy.sh, .github/workflows/ci.yml
=> Adding pulp-web to deploy job

.ci/scripts/deploy.sh
=> Fix pulp-operator deploy

.ci/scripts/pulp-operator-check-and-wait.sh, CHANGES/8294.misc, deploy/crds/pulpproject_v1beta1_pulp_crd.yaml
* Add definition of inputs for custom resource
* Add definition of status output
fixes #8294
https://pulp.plan.io/issues/8294
=> Define schema for Pulp CRD to allow for validation

.ci/ansible/galaxy/vars.yaml, .ci/ansible/vars.yaml, .ci/scripts/deploy.sh, .ci/scripts/pulp-operator-check-and-wait.sh, .github/workflows/ci.yml, .github/workflows/pr.yml, CHANGES/8370.misc, containers/images/pulp/Containerfile.web.j2, containers/images/pulp/container-assets/wait_on_postgres.py, deploy/crds/pulpproject_v1beta1_pulp_cr.ci.yaml
https://pulp.plan.io/issues/8370
closes #8370
=> Building and testing Galaxy

CHANGES/8402.feature, deploy/crds/pulpproject_v1beta1_pulp_crd.yaml, docs/roles/pulp-status.md, mkdocs.yml, playbook.yml, roles/pulp-api/tasks/get_node_ip.yml, roles/pulp-routes/templates/pulp.ingress.yaml.j2, roles/pulp-status/README.md, roles/pulp-status/meta/main.yml, roles/pulp-status/tasks/main.yml, roles/pulp-web/templates/pulp-web.service.yaml.j2
* Add status items to CRD
* Create status role to update CR
* Minor port cleanup for pulp-web
fixes #8402
https://pulp.plan.io/issues/8402
=> Operator will provide information data via custom resource status object

deploy/olm-catalog/pulp-operator/manifests/pulp-operator.clusterserviceversion.yaml
=> olm-catalog: Add displayName for the resource

.ci/scripts/galaxy_ng-tests.sh, CHANGES/8378.misc
* Script obtains token for admin
* Script checks access to expected repos
* Script displays http codes and exits with success or failure
fixes #8378
https://pulp.plan.io/issues/8378
Related to: https://github.com/ansible/galaxy_ng/pull/697
=> Add galaxy post deployment CI test script

deploy/olm-catalog/pulp-operator/manifests/pulp-operator.clusterserviceversion.yaml
Status are properly updated but not properly shown because of a mis-indentation.
[noissue]
=> CSV: Wrong indentation lead to status info not being shown

roles/pulp-worker/templates/pulp-worker.deployment.yaml.j2
=> Fix galaxy-importer /.ansible/tmp Permission Denied

CHANGES/5134.misc, CHANGES/5141.misc, CHANGES/5142.misc, CHANGES/5657.feature, CHANGES/7107.misc, CHANGES/7171.feature, CHANGES/7234.bugfix, CHANGES/8272.feature, CHANGES/8273.misc, CHANGES/8289.feature, CHANGES/8293.misc, CHANGES/8294.misc, CHANGES/8345.misc, CHANGES/8353.misc, CHANGES/8361.feature, CHANGES/8370.misc, CHANGES/8378.misc, CHANGES/8399.misc, CHANGES/8402.feature, CHANGES/8409.feature, CHANGES/8418.misc, CHANGES/8424.bugfix, CHANGES/8456.feature, docs/CHANGES.md
```
towncrier --version 0.2.0
```
[noissue]
=> Populate changelog with towncrier

.ci/ansible/galaxy/vars.yaml, .github/workflows/ci.yml, .github/workflows/pr.yml, deploy/crds/pulpproject_v1beta1_pulp_cr.galaxy.ci.yaml
=> Improve galaxy CI workflow

.github/workflows/ci.yml, .github/workflows/pr.yml
=> Use minikube from github actions

.ci/ansible/vars.yaml
=> Bump pulpcore

.ci/ansible/vars.yaml, .ci/ansible/web/vars.yaml, .ci/scripts/deploy.sh, .github/workflows/ci.yml
=> Fix deploy job

deploy/olm-catalog/pulp-operator/manifests/pulp-operator.clusterserviceversion.yaml, deploy/olm-catalog/pulp-operator/manifests/pulp.pulpproject.org_pulpbackups_crd.yml, deploy/olm-catalog/pulp-operator/manifests/pulp.pulpproject.org_pulprestores_crd.yml, deploy/olm-catalog/pulp-operator/manifests/pulp.pulpproject.org_pulps_crd.yml
=> Allow one to override custom_resource_key

deploy/olm-catalog/pulp-operator/manifests/pulp-operator.clusterserviceversion.yaml, deploy/olm-catalog/pulp-operator/manifests/pulp.pulpproject.org_pulps_crd.yml
=> olm manifests: Allow one to specify redis_image and postgres_image

roles/postgres/templates/postgres.yaml.j2
=> postgres: Allow to handle variable for different type of containers

deploy/crds/pulpproject_v1beta1_pulp_crd.yaml, deploy/olm-catalog/pulp-operator/manifests/pulp-operator.clusterserviceversion.yaml, deploy/olm-catalog/pulp-operator/manifests/pulp.pulpproject.org_pulps_crd.yml, roles/pulp-routes/defaults/main.yml, roles/pulp-status/defaults/main.yml, roles/pulp-status/tasks/main.yml, roles/pulp-web/defaults/main.yml, roles/pulp-web/templates/pulp-web.deployment.yaml.j2, roles/pulp-web/templates/pulp-web.service.yaml.j2
* Add ingress loadbalancer updates
* Add https/tls fixes
[noissue]
=> Improve ingress support and https/tls fixes

containers/images/pulp/container-assets/pulp-api
=> Do not show password in clear text in logs

.ci/ansible/vars.yaml, containers/images/pulp/Containerfile.core.j2
=> Temporarily pin pulpcore

.github/workflows/ci.yml, .github/workflows/pr.yml
=> Pin ansible version on CI

.ci/scripts/deploy.sh, bundle.Dockerfile
=> Adding bundle image

.ci/scripts/deploy.sh
=> Install OPM and deploy pulp-index

.ci/ansible/vars.yaml
=> Unpin pulpcore

.ci/scripts/deploy.sh, .github/workflows/ci.yml, .github/workflows/pr.yml
Currently, we only test pulp image before pushing pulp-web,
this PR adds a test for galaxy before pushing it, and ensure all images are pushed after tests
=> Refactoring CI

.ci/scripts/deploy.sh, .github/workflows/ci.yml
=> Fix nightly deploy for galaxy

.ci/ansible/galaxy/vars.yaml, .ci/ansible/galaxy/web/vars.yaml, .ci/ansible/pulp/vars.yaml, .ci/ansible/pulp/web/vars.yaml, .ci/scripts/deploy.sh
=> Separate pulp and galaxy vars on deploy job

CHANGES/8810.bugfix, deploy/crds/pulpproject_v1beta1_pulp_cr.ci.yaml, deploy/crds/pulpproject_v1beta1_pulp_cr.galaxy.ci.yaml, roles/pulp-api/defaults/main.yml, roles/pulp-api/templates/pulp-api.service.yaml.j2, roles/pulp-content/defaults/main.yml, roles/pulp-content/templates/pulp-content.service.yaml.j2
* Update nodeport templating for API and Content
fixes #8810
https://pulp.plan.io/issues/8810
=> Update nodeport templating in API and Content services

CHANGES/8832.bugfix, roles/pulp-api/defaults/main.yml, roles/pulp-api/tasks/main.yml, roles/pulp-api/templates/pulp-api.deployment.yaml.j2, roles/pulp-content/defaults/main.yml, roles/pulp-content/templates/pulp-content.deployment.yaml.j2, roles/pulp-resource-manager/defaults/main.yml, roles/pulp-resource-manager/templates/pulp-resource-manager.deployment.yaml.j2, roles/pulp-worker/defaults/main.yml, roles/pulp-worker/templates/pulp-worker.deployment.yaml.j2
* update is_file_storage fact to avoid collision
* Add default values
fixes #8832
https://pulp.plan.io/issues/8832
=> Fix collision on file_storage fact usage after pulp prefix cleanup

roles/pulp-api/tasks/main.yml
[noissue]
https://pulp.plan.io/issues/8832
=> Additional clean up from missed file_storage updates.

.ci/scripts/pulp_file-tests.sh, .ci/scripts/retry.sh, roles/pulp-web/templates/pulp-web.service.yaml.j2
=> Fix pulp_file test

containers/images/pulp/Containerfile.core.j2
=> Use fedora 34

.github/workflows/ci.yml, .github/workflows/pr.yml
=> Update molecule deps

deploy/crds/pulpproject_v1beta1_pulp_crd.yaml, deploy/olm-catalog/pulp-operator/manifests/pulp-operator.clusterserviceversion.yaml, deploy/olm-catalog/pulp-operator/manifests/pulp.pulpproject.org_pulps_crd.yml, playbook.yml, roles/postgres/templates/postgres.yaml.j2, roles/pulp-api/templates/pulp-api.deployment.yaml.j2, roles/pulp-content/templates/pulp-content.deployment.yaml.j2, roles/pulp-resource-manager/templates/pulp-resource-manager.deployment.yaml.j2, roles/pulp-web/templates/pulp-web.deployment.yaml.j2, roles/pulp-worker/templates/pulp-worker.deployment.yaml.j2, roles/redis/templates/redis.deployment.yaml.j2
=> image_pull_secret: Allow users to specify an image_pull_secret

CHANGES/8880.bugfix, roles/pulp-status/tasks/main.yml
* Update status check to use cluster local service DNS
fixes #8880
https://pulp.plan.io/issues/8880
=> Resolve Pulp status correctly when deployed in a separate namespace

CHANGES/8877.feature, deploy/crds/pulpproject_v1beta1_pulp_crd.yaml, deploy/olm-catalog/pulp-operator/manifests/pulp-operator.clusterserviceversion.yaml, deploy/olm-catalog/pulp-operator/manifests/pulp.pulpproject.org_pulps_crd.yml, roles/redis/templates/redis.pvc.yaml.j2
* Add field to custom resource definition
* Add display information to csv
* Update pvc template
fixes #8877
https://pulp.plan.io/issues/8877
=> Allow user to specify the storage class for the Redis PVC

playbook.yml
=> Do not set debug to True by default

docs/quickstart.md
[noissue]
@fao89 did a great job.
=> Few small edits

roles/pulp-api/tasks/get_node_ip.yml
* Include Ansible API in settings
[noissue]
=> Update settings with Ansible API.

.ci/scripts/deploy.sh, .ci/scripts/galaxy_ng-tests.sh
=> Fix galaxy test

roles/pulp-api/defaults/main.yml, roles/pulp-api/tasks/get_node_ip.yml
* Update settings values with pulp content service and port
[noissue]
=> Add pulp content settings

roles/backup/tasks/postgres.yml, roles/backup/tasks/secrets.yml, roles/postgres/tasks/main.yml, roles/postgres/tasks/migrate_data.yml, roles/pulp-api/tasks/admin_password_configuration.yml, roles/pulp-api/tasks/azure-storage-configuration.yml, roles/pulp-api/tasks/get_node_ip.yml, roles/pulp-api/tasks/main.yml, roles/pulp-api/tasks/s3-storage-configuration.yml, roles/pulp-web/tasks/load_route_tls_secret.yml, roles/restore/tasks/cleanup.yml, roles/restore/tasks/postgres.yml, roles/restore/tasks/secrets.yml
* Add no_log on secret creation
* Add no_log on k8_info for secrets
* Add no_log on set_fact handling for credentials
[noissue]
=> Use no_log to avoid credential leaks in operator log

.ci/scripts/deploy.sh
=> Fix opm index

docs/doc_requirements.txt
=> Fix publish docs

.ci/ansible/pulp/web/vars.yaml
=> Adding pulp_python webserver snippets

.ci/scripts/pulp_file-tests.sh
=> Fix CI test

.ci/scripts/images.py, .github/workflows/ci.yml
=> Build stable pulp/galaxy images nightly

README.md, deploy/olm-catalog/pulp-operator/manifests/pulp-operator.clusterserviceversion.yaml, mkdocs.yml
=> Update docs reference

containers/images/pulp/Containerfile.core.j2
=> Install openssl

.ci/scripts/deploy.sh, .ci/scripts/images.py, .github/workflows/ci.yml, .github/workflows/scripts/build_images.sh, .github/workflows/scripts/test_images.sh
=> Refactoring deploy job

.ci/assets/kubernetes/.kube-linter.yaml, .github/workflows/ci.yml, .github/workflows/pr.yml, deploy/operator.yaml, deploy/role.yaml
=> Add kube-linter

roles/pulp-api/tasks/db_fields_encryption_configuration.yml, roles/pulp-api/templates/pulp-db-fields-encryption.secret.yaml.j2, roles/pulp-content/templates/pulp-content.deployment.yaml.j2, roles/pulp-resource-manager/templates/pulp-resource-manager.deployment.yaml.j2, roles/pulp-worker/templates/pulp-worker.deployment.yaml.j2
=> Fix DB encryption

CHANGES/9217.misc, deploy/olm-catalog/pulp-operator/manifests/pulp-operator.clusterserviceversion.yaml
=> Make Ingress config visible on the main screen

molecule/default/tasks/pulp_test.yml
=> Fix molecule intermittent failure

CHANGES/9421.feature, playbooks/pulp.yml, roles/backup/tasks/postgres.yml, roles/postgres/README.md, roles/postgres/tasks/main.yml, roles/postgres/tasks/migrate_data.yml, roles/postgres/templates/postgres.secret.yaml.j2, roles/restore/tasks/postgres.yml
=> Added support to override PosgreSQL sslmode

.ci/scripts/validate_commit_message.py, .github/workflows/pr.yml, CHANGES/206.misc
=> Enable github issues

.ci/scripts/galaxy_ng-tests.sh
=> Improve galaxy tests

containers/images/pulp/container-assets/pulp-resource-manager, containers/images/pulp/container-assets/pulp-worker
=> Due to PATH env export don't speficy full path for bin

roles/pulp-api/defaults/main.yml, roles/pulp-api/tasks/s3-storage-configuration.yml
=> Fix s3_secret_data_avaiable typo

.ci/assets/kubernetes/pulp-container-auth.secret.yaml, .ci/scripts/galaxy_ng-tests.sh, .gitleaks.toml, bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/samples/pulpproject_v1beta1_pulp_cr.galaxy.ci.yaml, config/samples/pulpproject_v1beta1_pulp_cr.galaxy.container.ci.yaml, roles/backup/templates/container_token_secret.yaml.j2, roles/restore/templates/container_token_secret.yaml.j2, up.sh
=> Test galaxy EE

bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/crd/bases/pulpproject_v1beta1_pulp_crd.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, roles/pulp-api/defaults/main.yml, roles/pulp-api/tasks/main.yml, roles/pulp-api/tasks/sso-configuration.yml
=> SSO: Allow one to provide SSO secret

.ci/scripts/molecule.sh, config/samples/pulpproject_v1beta1_pulp_cr.molecule.ci.yaml, molecule/default/tasks/pulp_test.yml
=> Adding container auth secret to CR

roles/backup/tasks/init.yml, roles/backup/tasks/secrets.yml, roles/backup/tasks/update_status.yml, roles/backup/templates/sso_secret.yaml.j2, roles/restore/tasks/cleanup.yml, roles/restore/tasks/init.yml, roles/restore/tasks/secrets.yml, roles/restore/templates/sso_secret.yaml.j2
=> SSO: Backup and restore

Makefile, docs/quickstart.md, up.sh
=> Update installation docs

CHANGES/227.feature, CHANGES/229.bugfix, CHANGES/231.feature, CHANGES/232.feature, Makefile, bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/manifests/pulp.pulpproject.org_pulps.yaml, config/manager/kustomization.yaml, docs/CHANGES.md
=> Release 0.5.0

Makefile
=> Generate yaml with pulp config

roles/restore/tasks/secrets.yml
Signed-off-by: Julen Landa Alustiza <jlanda@redhat.com>
=> Fix typo [noissue]

containers/images/pulp/Containerfile.core.j2, containers/images/pulp/container-assets/wait_on_postgres.py
=> Use python3 + bump to fedora 35

roles/backup/templates/sso_secret.yaml.j2
=> Typo: Fix keycloack to keycloak

containers/images/pulp/Containerfile.core.j2
=> Revert to fedora 34

containers/images/pulp/Containerfile.web.j2, roles/pulp-web/defaults/main.yml
=> Fix nginx config

CHANGES/289.bugfix, CHANGES/295.bugfix
=> Adding missing changelog entries

roles/pulp-api/tasks/sso-configuration.yml, roles/pulp-api/templates/pulp-server.secret.yaml.j2
Reverts pulp/pulp-operator#284
=> Revert "sso: Add galaxy_verify_keycloack_ssl_certs as part of the config"

CHANGES/289.bugfix, CHANGES/295.bugfix, Makefile, bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, docs/CHANGES.md
=> Release 0.6.0

CHANGES/302.bugfix, CHANGES/303.bugfix, roles/pulp-content/defaults/main.yml, roles/pulp-worker/defaults/main.yml
=> Raise Limits to avoid OOMKill

playbooks/pulp.yml, roles/postgres/defaults/main.yml, roles/pulp-api/defaults/main.yml, roles/pulp-content/defaults/main.yml, roles/pulp-resource-manager/defaults/main.yml, roles/pulp-web/defaults/main.yml, roles/pulp-worker/defaults/main.yml, roles/redis/defaults/main.yml
=> Fix raw_spec typo

roles/pulp-api/tasks/get_node_ip.yml
=> Fix typo on token auth var

CHANGES/309.bugfix, playbooks/pulp.yml, roles/postgres/templates/postgres.secret.yaml.j2, roles/postgres/templates/postgres.yaml.j2, roles/pulp-api/templates/pulp-api.deployment.yaml.j2, roles/pulp-content/templates/pulp-content.deployment.yaml.j2, roles/pulp-resource-manager/templates/pulp-resource-manager.deployment.yaml.j2, roles/pulp-worker/templates/pulp-worker.deployment.yaml.j2, roles/redis/templates/redis.service.yaml.j2
https://kubernetes.io/docs/concepts/services-networking/service/#environment-variables
closes #309
=> Renamed services to avoid overwriting environment variables

.ci/assets/kubernetes/pulp-container-auth.secret.yaml, CHANGES/313.feature, roles/backup/tasks/secrets.yml, roles/pulp-api/defaults/main.yml, roles/pulp-api/tasks/main.yml, roles/pulp-api/templates/pulp-api.deployment.yaml.j2
=> Support cert-manager format on container token secret

CHANGES/309.bugfix, CHANGES/313.feature, CHANGES/315.feature, Makefile, bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, docs/CHANGES.md
=> Release 0.7.0

.ci/assets/kubernetes/azurite.yaml, .ci/assets/kubernetes/pulp-object-storage.aws.secret.yaml, .ci/assets/kubernetes/pulp-object-storage.azure.secret.yaml, .ci/scripts/prepare-object-storage.sh, .github/workflows/ci.yml, .github/workflows/pr.yml, .gitleaks.toml, config/samples/pulpproject_v1beta1_pulp_cr.galaxy.azure.ci.yaml, roles/backup/tasks/secrets.yml, roles/backup/templates/azure_secret.yaml.j2, roles/pulp-api/tasks/azure-storage-configuration.yml, up.sh
=> Adding azure test

.ci/ansible/galaxy/vars.yaml
=> Bump pulpcore on galaxy image

.github/workflows/scripts/show_logs.sh
=> Skip minikube metrics when it fails

CHANGES/323.bugfix, playbooks/pulp.yml, roles/pulp-api/tasks/main.yml
=> Made Redis optional when installing pulp

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/task.md
=> Adding issue template

CHANGES/326.bugfix, config/rbac/auth_proxy_role_binding.yaml, config/rbac/leader_election_role_binding.yaml, config/rbac/role_binding.yaml
Closes #326.
This is the first time to send PR to this project, so please let me know if I'm on the wrong way. I'm not sure if `CHANGES/326.bugfix` is required, but I add it just in case. Feel free to reject or add commits to fix my PR.
Thanks 😃 
=> Remove hard-coded namespaces

.ci/ansible/pulp/vars.yaml
=> All content on latest

.ci/ansible/pulp/web/vars.yaml, containers/images/pulp/Containerfile.core.j2
=> Fix pulp image

CHANGES/330.bugfix, roles/pulp-routes/defaults/main.yml, roles/pulp-web/defaults/main.yml
=> Made web image and ingress to have the same max_body_size

CHANGES/332.bugfix, roles/pulp-api/templates/pulp-api.deployment.yaml.j2, roles/pulp-web/templates/pulp-web.deployment.yaml.j2
=> Fixes pulp-api and pulp-web liveness probes

.github/workflows/ci.yml
=> Slack notification on error

.github/workflows/ci.yml
=> Improve slack message

.github/workflows/ci.yml
=> Fix link on slack payload

CHANGES/337.bugfix, config/manifests/bases/pulp-operator.clusterserviceversion.yaml
=> Fix token authentication

roles/pulp-routes/defaults/main.yml
=> Adding NGINX annotation

docs/quickstart.md
=> Fix status endpoint on quickstart docs

CHANGES/344.feature, bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/manifests/pulp.pulpproject.org_pulps.yaml, config/crd/bases/pulpproject_v1beta1_pulp_crd.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, roles/postgres/defaults/main.yml, roles/postgres/templates/postgres.yaml.j2
=> Add ability to configure extra args for postgres

CHANGES/345.feature, bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/manifests/pulp.pulpproject.org_pulps.yaml, config/crd/bases/pulpproject_v1beta1_pulp_crd.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, roles/pulp-api/templates/pulp-api.deployment.yaml.j2, roles/pulp-content/templates/pulp-content.deployment.yaml.j2, roles/pulp-resource-manager/templates/pulp-resource-manager.deployment.yaml.j2, roles/pulp-web/defaults/main.yml, roles/pulp-web/templates/pulp-web.deployment.yaml.j2, roles/pulp-worker/templates/pulp-worker.deployment.yaml.j2
=> Add the ability to specify topologySpreadConstraints

CHANGES/346.feature, bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/manifests/pulp.pulpproject.org_pulps.yaml, config/crd/bases/pulpproject_v1beta1_pulp_crd.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, roles/pulp-web/defaults/main.yml, roles/pulp-web/templates/pulp-web.service.yaml.j2
=> Allow service annotations not only for LoadBalancer type

CHANGES/348.feature, bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/manifests/pulp.pulpproject.org_pulps.yaml, config/crd/bases/pulpproject_v1beta1_pulp_crd.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, roles/postgres/defaults/main.yml, roles/postgres/templates/postgres.yaml.j2, roles/pulp-api/templates/pulp-api.deployment.yaml.j2, roles/pulp-content/templates/pulp-content.deployment.yaml.j2, roles/pulp-resource-manager/templates/pulp-resource-manager.deployment.yaml.j2, roles/pulp-web/defaults/main.yml, roles/pulp-web/templates/pulp-web.deployment.yaml.j2, roles/pulp-worker/templates/pulp-worker.deployment.yaml.j2
=> Support nodeSelector and tolerations

CHANGES/354.bugfix, playbooks/pulp.yml
=> Ensure the operator works with pre-defined TLS secret

playbooks/pulp.yml
=> Fix ansible certs dir

containers/images/pulp/Containerfile.core.j2
=> Pin azure-storage-blob

CHANGES/344.feature, CHANGES/345.feature, CHANGES/346.feature, CHANGES/348.feature, CHANGES/354.bugfix, Makefile, bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, docs/CHANGES.md
=> Release 0.8.0

config/manager/manager.yaml, roles/postgres/templates/postgres.yaml.j2, roles/pulp-api/templates/pulp-api.deployment.yaml.j2, roles/pulp-content/templates/pulp-content.deployment.yaml.j2, roles/pulp-web/templates/pulp-web.deployment.yaml.j2, roles/pulp-worker/templates/pulp-worker.deployment.yaml.j2, roles/redis/templates/redis.deployment.yaml.j2
=> Disable node affinity check on kubelinter

.ci/scripts/galaxy_ng-tests.sh
=> Follow redirects on galaxy tests

bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/manifests/pulp.pulpproject.org_pulpbackups.yaml, config/crd/bases/pulpproject_v1beta1_pulpbackup_crd.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, roles/backup/tasks/update_status.yml, roles/pulp-status/tasks/main.yml, roles/restore/tasks/init.yml
=> Fix azure test

CHANGES/374.misc, Dockerfile, Makefile, bundle.Dockerfile, bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/manifests/pulp.pulpproject.org_pulps.yaml, bundle/metadata/annotations.yaml, bundle/tests/scorecard/config.yaml, config/crd/kustomization.yaml, config/default/manager_auth_proxy_patch.yaml, config/manager/kustomization.yaml, config/manager/manager.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, config/rbac/auth_proxy_role.yaml, config/rbac/role.yaml, config/samples/kustomization.yaml, config/scorecard/kustomization.yaml, config/scorecard/patches/basic.config.yaml, config/scorecard/patches/olm.config.yaml, config/testing/debug_logs_patch.yaml, roles/backup/templates/container_token_secret.yaml.j2, roles/backup/templates/galaxy_signing_secret.yaml.j2, roles/common/templates/pulp-operator-sa.yaml.j2, roles/pulp-routes/templates/pulp.ingress.yaml.j2, roles/restore/templates/container_token_secret.yaml.j2, roles/restore/templates/galaxy_signing_secret.yaml.j2
=> Upgrade operator-sdk

CHANGES/378.bugfix, roles/backup/tasks/error_handling.yml, roles/restore/tasks/error_handling.yml
closes #378
Ref: https://github.com/ansible/ansible/issues/45199
=> Fix backup/restore events

CHANGES/380.feature, roles/backup/tasks/init.yml
=> Enable backup for ReadWriteOnce access mode

CHANGES/343.feature, CHANGES/362.feature, CHANGES/366.feature, CHANGES/374.misc, CHANGES/378.bugfix, CHANGES/380.feature, Makefile, bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, docs/CHANGES.md
=> Release 0.9.0

config/manager/manager.yaml
See the associated awx-operator PR for context - https://github.com/ansible/awx-operator/pull/894
=>  Look for a specific pull secret, needed for some deployment scenarios

CHANGES/392.feature, containers/images/pulp/container-assets/pulp-api, containers/images/pulp/container-assets/pulp-content, roles/pulp-api/defaults/main.yml, roles/pulp-api/templates/pulp-api.deployment.yaml.j2, roles/pulp-content/defaults/main.yml, roles/pulp-content/templates/pulp-content.deployment.yaml.j2
=> Add configurable workers for pulp-api and pulp-content

CHANGES/394.bugfix, Dockerfile, config/samples/pulpproject_v1beta1_pulp_cr.galaxy.ci.yaml, roles/pulp-api/tasks/container_auth_configuration.yml, roles/pulp-api/tasks/main.yml, roles/pulp-api/templates/pulp-container-auth.secret.yaml.j2, up.sh
=> Provide default values for container registry

.ci/scripts/kubelinter.sh, CHANGES/386.misc, CHANGES/388.bugfix, CHANGES/390.feature, CHANGES/392.feature, CHANGES/394.bugfix, Dockerfile, Makefile, bundle.Dockerfile, bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, bundle/tests/scorecard/config.yaml, config/manager/kustomization.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, config/scorecard/patches/basic.config.yaml, config/scorecard/patches/olm.config.yaml, docs/CHANGES.md
=> Release 0.10.0

.github/workflows/ci.yml, .github/workflows/pulp_images.yml
=> Fix deploy

.github/workflows/scripts/show_logs.sh, roles/postgres/templates/postgres.yaml.j2
=> Fix postgres authentication errors

CHANGES/385.bugfix, Dockerfile
…conciliation loops
closes #375
(cherry picked from commit 65827769e53824805b38eec8fce21a965603eff9)
=> Set reconcile period to 0s to resolve issue with reconciliation loop not converging

.ci/scripts/pulp_tests.sh
=> Fix pulp tests

docs/quickstart.md
=> Clarify s3 credentials for Secret.

docs/roles/common.md
=> Fix broken docs

.ci/scripts/backup_and_restore.sh, .github/workflows/scripts/show_logs.sh, CHANGES/407.misc, Makefile, playbooks/pulp.yml
=> Fix redhat-operators-pull-secret warning

.github/stale.yml
https://github.com/probot/stale
[noissue]
=> Enable stalebot

CHANGES/418.bugfix, CHANGES/418.feature, config/crd/bases/pulpproject_v1beta1_pulp_crd.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, roles/pulp-routes/defaults/main.yml, roles/pulp-routes/templates/pulp.ingress.yaml.j2, roles/pulp-web/templates/pulp-web.configmap.yaml.j2
=> Make timeouts configurable

containers/images/pulp/Containerfile.core.j2
=> Add LDAP package

.ci/scripts/backup_and_restore.sh, .ci/scripts/kubelinter.sh, .ci/scripts/pulp-operator-check-and-wait.sh, .github/workflows/scripts/show_logs.sh, CHANGES/427.bugfix, roles/backup/templates/secrets.yaml.j2, roles/restore/defaults/main.yml, roles/restore/tasks/deploy_pulp.yml, roles/restore/tasks/init.yml, roles/restore/tasks/secrets.yml, roles/restore/templates/postgres.secret.yaml.j2
=> Improve restore role

roles/pulp-content/templates/pulp-content.deployment.yaml.j2, roles/pulp-worker/templates/pulp-worker.deployment.yaml.j2
=> Mount signing keys on content and workers

config/samples/pulpproject_v1beta1_pulp_cr.galaxy.azure.ci.yaml, config/samples/pulpproject_v1beta1_pulp_cr.galaxy.ci.yaml, roles/pulp-api/tasks/main.yml, roles/pulp-web/tasks/main.yml
=> Remove galaxy root workaround

CHANGES/440.bugfix, roles/pulp-api/tasks/azure-storage-configuration.yml
=> Ensure azure_connection_string is optional

CHANGES/443.feature, CHANGES/447.bugfix, Makefile, bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, docs/CHANGES.md
=> Release 0.12.0

.github/workflows/pulp_images.yml, containers/compose/settings.py
=> Fix compose CI

CHANGES/435.feature, molecule/default/tasks/pulp_test.yml, roles/postgres/tasks/main.yml, roles/postgres/tasks/migrate_data.yml, roles/postgres/tasks/upgrade_postgres.yml, roles/pulp-api/tasks/admin_password_configuration.yml, roles/pulp-api/tasks/azure-storage-configuration.yml, roles/pulp-api/tasks/container_auth_configuration.yml, roles/pulp-api/tasks/db_fields_encryption_configuration.yml, roles/pulp-api/tasks/get_node_ip.yml, roles/pulp-api/tasks/main.yml, roles/pulp-api/tasks/s3-storage-configuration.yml, roles/pulp-api/tasks/signing_service.yml, roles/pulp-api/tasks/sso-configuration.yml, roles/pulp-content/tasks/main.yml, roles/pulp-resource-manager/tasks/main.yml, roles/pulp-status/tasks/main.yml, roles/pulp-web/tasks/main.yml, roles/pulp-worker/tasks/main.yml, watches.yaml
=> Improve status conditions field

.github/workflows/ci.yml, .github/workflows/pr.yml, .github/workflows/scripts/show_logs.sh
=> Improve show_logs

.github/workflows/ci.yml, .github/workflows/pr.yml
=> Downgrade minikube

roles/pulp-content/templates/pulp-content.deployment.yaml.j2
=> Use head request on content readiness

CHANGES/467.bugfix, roles/pulp-api/tasks/container_auth_configuration.yml, roles/pulp-api/tasks/db_fields_encryption_configuration.yml
=> Remove ownerReferences from DB fields encryption secret

CHANGES/461.misc, roles/pulp-api/tasks/get_node_ip.yml, roles/pulp-status/tasks/main.yml
=> Closes #461

.ci/scripts/backup_and_restore.sh, roles/postgres/tasks/main.yml, roles/restore/tasks/deploy_pulp.yml, roles/restore/tasks/main.yml
=> Include after restore logs

CHANGES/435.feature, CHANGES/455.feature, CHANGES/461.misc, CHANGES/466.misc, CHANGES/467.bugfix, Makefile, bundle.Dockerfile, bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, bundle/tests/scorecard/config.yaml, config/manager/controller_manager_config.yaml, config/manager/kustomization.yaml, docs/CHANGES.md
=> Release 0.13.0

containers/images/pulp/Containerfile.core.j2, containers/images/pulp/container-assets/readyz.py
=> Fix requests warnings

.ci/ansible/galaxy/vars.yaml, .github/workflows/ci.yml, .github/workflows/pr.yml
=> Use latest minikube

.github/workflows/scripts/test_images.sh
=> Fix pulp images deploy

Dockerfile, Makefile, bundle.Dockerfile, bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, bundle/tests/scorecard/config.yaml, config/scorecard/patches/basic.config.yaml, config/scorecard/patches/olm.config.yaml
=> Bump SDK to 1.22.1

.ci/scripts/backup_and_restore.sh, .github/workflows/ci.yml, .github/workflows/pr.yml, insta-demo/pulp-insta-demo.sh
=> Remove timeout on kubectl wait

.ci/prow/Dockerfile.ci-operator, .ci/prow/openshift-test.sh, .ci/scripts/galaxy_ng-tests.sh, .ci/scripts/molecule.sh, .ci/scripts/pulp_tests.sh, Dockerfile, config/samples/kustomization.yaml, config/samples/pulpproject_v1beta1_pulp_cr.galaxy.ocp.ci.yaml, config/samples/pulpproject_v1beta1_pulp_cr.ocp.ci.yaml
=> Adapt tests for OCP

OWNERS
=> Adding prow owners

CHANGES/489.misc, containers/images/pulp/Containerfile.core.j2, containers/images/pulp/container-assets/route_paths.py, playbooks/pulp.yml, roles/common/defaults/main.yml, roles/common/tasks/main.yml, roles/pulp-api/tasks/get_node_ip.yml, roles/pulp-routes/tasks/main.yml
=> Add nginx snippet parser

.ci/scripts/galaxy_ng-tests.sh
=> Speed up galaxy tests

.ci/prow/openshift-test.sh, Makefile, bundle/manifests/pulp-operator.clusterserviceversion.yaml
=> Use built catalog

.ci/prow/openshift-test.sh
=> Improve API waiting on OCP test

.ci/prow/openshift-test.sh
=> Temporarily disable OCP test

.ci/prow/openshift-test.sh, config/samples/pulpproject_v1beta1_pulp_cr.galaxy.ocp.ci.yaml, config/samples/pulpproject_v1beta1_pulp_cr.ocp.ci.yaml
=> Enable OCP test

.ci/prow/openshift-test.sh
=> Verify request to route

.ci/scripts/backup_and_restore.sh
=> Fix backup CI script

.ci/assets/kubernetes/pulp-object-storage.aws.secret.yaml, .ci/scripts/backup_and_restore.sh, .ci/scripts/prepare-object-storage.sh, .github/workflows/ci.yml, .github/workflows/pr.yml, .gitleaks.toml, config/samples/pulpproject_v1beta1_pulp_cr.galaxy.s3.ci.yaml, roles/pulp-api/defaults/main.yml, roles/pulp-api/tasks/main.yml, roles/pulp-api/tasks/s3-storage-configuration.yml, roles/pulp-api/templates/pulp-api.deployment.yaml.j2, roles/pulp-web/templates/pulp-web.deployment.yaml.j2, up.sh
=> Enable minio test

api/v1alpha1/pulp_types.go, api/v1alpha1/pulpbackup_types.go, api/v1alpha1/pulprestore_types.go, bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml
https://sdk.operatorframework.io/docs/building-operators/golang/references/markers/
=> Adding OLM descriptors

config/manager/manager.yaml
=> Bump manager limit to match AWX

Dockerfile, Makefile, bundle.Dockerfile, bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, bundle/tests/scorecard/config.yaml, config/default/kustomization.yaml, config/default/manager_auth_proxy_patch.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, config/scorecard/patches/basic.config.yaml, config/scorecard/patches/olm.config.yaml, config/testing/kustomization.yaml, molecule/default/kustomize.yml
=> Improve OCP UI + update operator-sdk

.ci/scripts/backup_and_restore.sh, .ci/scripts/galaxy_ng-tests.sh, .github/workflows/ci.yml, .github/workflows/scripts/test_images.sh, api/v1alpha1/pulp_types.go, bundle.Dockerfile, bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/manifests/repo-manager.pulpproject.org_pulps.yaml, bundle/metadata/annotations.yaml, config/crd/bases/repo-manager.pulpproject.org_pulps.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, config/rbac/role.yaml, config/samples/galaxy.azure.ci.yaml, config/samples/galaxy.s3.ci.yaml, config/samples/galaxy.yaml, config/samples/repo-manager_v1alpha1_pulp.yaml, config/samples/repo-manager_v1alpha1_pulpbackup.yaml, config/samples/repo-manager_v1alpha1_pulprestore.yaml, controllers/pulp/api.go, controllers/pulp/common.go, controllers/pulp/content.go, controllers/pulp/controller.go, controllers/pulp/database.go, controllers/pulp/redis.go, controllers/pulp/route.go, controllers/pulp/status.go, go.mod, go.sum, main.go
=> Adding route support

.ci/assets/kubernetes/catalog.yaml, .github/workflows/ci.yml
=> Adding catalog example

api/v1alpha1/pulp_types.go, bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/manifests/repo-manager.pulpproject.org_pulps.yaml, config/crd/bases/repo-manager.pulpproject.org_pulps.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, controllers/pulp/route.go
=> Add content_path_prefix

controllers/pulp/controller.go
=> Raise error when multiple object storages

.ci/scripts/backup_and_restore.sh, .ci/scripts/local.sh, .github/workflows/ci.yml, .github/workflows/scripts/show_logs.sh, Makefile, config/local/kustomization.yaml, config/local/namespace.yaml
=> CI: Run operator locally

bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/manager/manager.yaml, controllers/pulp/controller.go
=> Pre-seed redhat-operators-pull-secret

bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/samples/simple-external-db.yaml, config/samples/simple-sso.yaml, config/samples/simple.yaml, controllers/pulp/api.go, controllers/pulp/content.go, controllers/pulp/controller.go, controllers/pulp/controller_test.go, controllers/pulp/database.go, controllers/pulp/redis.go, controllers/pulp/web.go, controllers/pulp/worker.go
=> Use relatedImages to make disconnected deployments possible

controllers/pulp/api.go
=> Configure service addresses based on ingressType

.github/workflows/ci.yml, README.md, docs/container.md, docs/contributing.md, docs/quickstart.md, docs/roles/backup.md, docs/roles/common.md, docs/roles/postgres.md, docs/roles/pulp-api.md, docs/roles/pulp-content.md, docs/roles/pulp-resource-manager.md, docs/roles/pulp-routes.md, docs/roles/pulp-status.md, docs/roles/pulp-web.md, docs/roles/pulp-worker.md, docs/roles/redis.md, docs/roles/restore.md, mkdocs.yml
=> Update docs for go based operator

.ci/prow/Dockerfile.ci-operator
=> Fix OCP image

containers/images/pulp/container-assets/route_paths.py
=> Route workaround for rewrite case

CHANGES/561.bugfix, roles/redis/templates/redis.deployment.yaml.j2
=> Adding NodeSelector/Toleration to Redis Deployment

controllers/backup/controller.go, controllers/backup/cr.go, controllers/backup/database.go, controllers/backup/pulp_dir.go, controllers/backup/secret.go, controllers/pulp/controller.go, controllers/pulp/sso.go, controllers/pulp/suite_test.go, controllers/restore/controller.go, controllers/restore/deploy.go, controllers/restore/pulp_dir.go, controllers/restore/secret.go, main.go
=> Improving log

.ci/assets/kubernetes/signing_scripts.configmap.yaml, CHANGES/564.feature, containers/images/pulp/Containerfile.core.j2, containers/images/pulp/container-assets/pulp-api, playbooks/pulp.yml, roles/pulp-api/templates/pulp-api.deployment.yaml.j2
=> Add support for pulp_container signing service

containers/images/pulp/container-assets/route_paths.py
=> Fix typo on route

.ci/ansible/galaxy/vars.yaml
=> Fix galaxy image

.ci/assets/kubernetes/signing_scripts.configmap.yaml, containers/images/pulp/Containerfile.core.j2, containers/images/pulp/container-assets/pulp-api, controllers/pulp/api.go, controllers/pulp/utils.go
=> Go: Add support for pulp_container signing service

Makefile, README.md, controllers/backup/README.md, controllers/pulp/README.md, controllers/restore/README.md, docs/backup.md, docs/container.md, docs/contributing.md, docs/pulp.md, docs/restore.md
=> Improving go-based docs

.ci/ansible/galaxy/vars.yaml, bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/manifests/repo-manager.pulpproject.org_pulpbackups.yaml, bundle/manifests/repo-manager.pulpproject.org_pulprestores.yaml, bundle/manifests/repo-manager.pulpproject.org_pulps.yaml, config/crd/bases/repo-manager.pulpproject.org_pulpbackups.yaml, config/crd/bases/repo-manager.pulpproject.org_pulprestores.yaml, config/crd/bases/repo-manager.pulpproject.org_pulps.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, containers/images/pulp/container-assets/route_paths.py, controllers/pulp/README.md, controllers/pulp/redis.go
=> Keeping up with ansible-based

CHANGES/572.feature, api/v1alpha1/pulprestore_types.go, controllers/restore/deploy.go
=> Allow to control the restore deployment replicas

.github/workflows/kanban.yml
=> Update kanban workflow

CHANGES/580.bugfix, controllers/backup/controller.go
=> Fix backup issue when a PVC is manually provided

.github/workflows/nightly.yml
=> Update go docs nightly

CHANGES/513.feature, api/v1alpha1/pulp_types.go, config/crd/bases/repo-manager.pulpproject.org_pulprestores.yaml, config/crd/bases/repo-manager.pulpproject.org_pulps.yaml, controllers/pulp/README.md, controllers/pulp/api.go, controllers/pulp/content.go, controllers/pulp/controller.go, controllers/pulp/utils.go, controllers/pulp/worker.go, controllers/restore/README.md, docs/customCA.md, mkdocs.yml
closes #513
https://issues.redhat.com/browse/AAP-5094
=> Add option to mount custom CA

.ci/scripts/pulp_tests.sh, config/samples/galaxy.azure.ci.yaml, config/samples/galaxy.s3.ci.yaml, config/samples/galaxy.yaml, config/samples/pulpproject_v1beta1_pulp_cr.galaxy.ocp.ci.yaml, config/samples/pulpproject_v1beta1_pulp_cr.ocp.ci.yaml, config/samples/repo-manager_v1alpha1_pulp.yaml, config/samples/simple-external-db.yaml, config/samples/simple-sso.yaml, config/samples/simple.yaml
[noissue]
(cherry picked from commit 7781a019007638c5f07a1e7c3f8d2e2c0fa5c502)
=> Enable container tests

CHANGES/593.doc, docs/storage.md
=> Add samples for Object Storage secret

docs/faq.md, mkdocs.yml
[noissue]
(not a fix, but it is related to #521)
=> Add FAQ doc section

CHANGES/590.misc, containers/images/pulp/Containerfile.core.j2, containers/images/pulp/container-assets/pulp-api, playbooks/pulp.yml
=> Run collectstatic during image build

CHANGES/601.bugfix, bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/manifests/repo-manager.pulpproject.org_pulprestores.yaml, bundle/manifests/repo-manager.pulpproject.org_pulps.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/pulp/controller.go
=> Add serviceaccounts permission

bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/default/manager_auth_proxy_patch.yaml, config/samples/repo-manager_v1alpha1_pulp.yaml
=> Update example CR + update the bundle

CHANGES/610.bugfix, roles/backup/tasks/init.yml
Resolves https://github.com/pulp/pulp-operator/issues/610
=> Take into account backup_pvc when removing owner references

CHANGES/436.feature, CHANGES/489.misc, CHANGES/561.bugfix, CHANGES/564.feature, CHANGES/590.misc, CHANGES/610.bugfix, Makefile, bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, docs/CHANGES.md
=> Release 0.14.0

CHANGES/605.doc, bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/default/manager_auth_proxy_patch.yaml, docs/configuring/logLevel.md
=> Stacktrace enabled only for above "panic" level.

bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/manifests/pulp.pulpproject.org_pulprestores.yaml, config/crd/bases/pulpproject_v1beta1_pulprestore_crd.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml
=> Storage type as enum

CHANGES/600.bugfix, config/rbac/role.yaml, controllers/pulp/api.go, controllers/pulp/content.go, controllers/pulp/controller.go, controllers/pulp/database.go, controllers/pulp/rbac.go, controllers/pulp/route.go, controllers/pulp/status.go, controllers/pulp/utils.go, controllers/pulp/web.go, controllers/pulp/worker.go, docs/tshoot/install.md
=> Fix .status.condition not reflecting real state

CHANGES/619.doc, api/v1alpha1/pulp_types.go, config/crd/bases/repo-manager.pulpproject.org_pulps.yaml, config/samples/simple-external-db.yaml, controllers/pulp/README.md, docs/configuring/database.md, mkdocs.yml
=> Added documentation to config database

CHANGES/436.feature, CHANGES/489.misc, api/v1alpha1/pulprestore_types.go, bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/manifests/repo-manager.pulpproject.org_pulprestores.yaml, bundle/manifests/repo-manager.pulpproject.org_pulps.yaml, config/crd/bases/repo-manager.pulpproject.org_pulprestores.yaml, config/crd/bases/repo-manager.pulpproject.org_pulps.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, docs/CHANGES.md
=> Updates from main branch

CHANGES/622.bugfix, api/v1alpha1/pulp_types.go, config/crd/bases/repo-manager.pulpproject.org_pulps.yaml, controllers/pulp/README.md
=> Remove some default db values

CHANGES/627.feature, config/crd/bases/repo-manager.pulpproject.org_pulps.yaml, controllers/pulp/README.md, controllers/pulp/api.go, controllers/pulp/content.go, controllers/pulp/web.go, controllers/pulp/worker.go
=> Modify the UID that runs the container process

.github/workflows/scripts/show_logs.sh
=> Ensure CI logs

bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/manifests/pulp.pulpproject.org_pulpbackups.yaml, bundle/manifests/pulp.pulpproject.org_pulps.yaml, config/crd/bases/pulpproject_v1beta1_pulp_crd.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, roles/pulp-api/templates/pulp-api.deployment.yaml.j2, roles/pulp-content/templates/pulp-content.deployment.yaml.j2, roles/pulp-resource-manager/templates/pulp-resource-manager.deployment.yaml.j2, roles/pulp-web/templates/pulp-web.deployment.yaml.j2, roles/pulp-worker/templates/pulp-worker.deployment.yaml.j2, roles/redis/defaults/main.yml, roles/redis/templates/redis.deployment.yaml.j2
=> Add a field to configure the deployment strategy

.github/workflows/nightly.yml, README.md, bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, docs/quickstart.md
=> Update docs workflow

README.md
=> Notify that project is still in alpha stage

docs/container.md
=> Update container docs

README.md, bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml
=> Remove link to redmine

CHANGES/657.feature, Makefile, bundle/manifests/pulp-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, config/rbac/role.yaml, config/rbac/role_binding.yaml, controllers/backup/controller.go, controllers/pulp/controller.go, controllers/restore/controller.go, main.go
=> Make the operator namespace-scoped

roles/pulp-api/templates/pulp-api.deployment.yaml.j2, roles/pulp-content/templates/pulp-content.deployment.yaml.j2, roles/pulp-resource-manager/templates/pulp-resource-manager.deployment.yaml.j2, roles/pulp-web/templates/pulp-web.deployment.yaml.j2, roles/pulp-worker/templates/pulp-worker.deployment.yaml.j2, roles/redis/templates/redis.deployment.yaml.j2
=> Fix strategy

.github/workflows/ci.yml, PROJECT, api/v1alpha1/pulp_webhook.go, api/v1alpha1/webhook_suite_test.go, config/certmanager/certificate.yaml, config/certmanager/kustomization.yaml, config/certmanager/kustomizeconfig.yaml, config/crd/kustomization.yaml, config/default/kustomization.yaml, config/default/manager_webhook_patch.yaml, config/default/webhookcainjection_patch.yaml, config/rbac/role.yaml, config/webhook/kustomization.yaml, config/webhook/kustomizeconfig.yaml, config/webhook/manifests.yaml, config/webhook/service.yaml, controllers/pulp/controller.go, go.mod, go.sum, main.go
=> Add validation webhook to handle field removal

CHANGES/646.bugfix, api/v1alpha1/pulp_types.go, config/crd/bases/repo-manager.pulpproject.org_pulps.yaml, controllers/backup/secret.go, controllers/pulp/README.md, controllers/pulp/api.go, controllers/pulp/controller.go, controllers/pulp/status.go, controllers/restore/secret.go
=> Set container-token-secret field immutable

roles/pulp-web/templates/pulp-web.configmap.yaml.j2
ref: [AAP-4997](https://issues.redhat.com//browse/AAP-4997)
[noissue]
=> Fix IPv6 issue

CHANGES/646.bugfix, api/v1alpha1/pulp_types.go, config/crd/bases/repo-manager.pulpproject.org_pulps.yaml, controllers/pulp/README.md, controllers/pulp/api.go, controllers/pulp/controller.go, controllers/pulp/status.go, controllers/pulp/utils.go
=> Set admin_password_secret field immutable

CHANGES/646.bugfix, controllers/pulp/controller.go, controllers/pulp/rbac.go
=> Add image_pull_secrets reconciliation logic

CHANGES/646.bugfix, controllers/pulp/api.go, controllers/pulp/content.go, controllers/pulp/worker.go
=> Add mount_trusted_ca reconciliation logic

CHANGES/681.doc, docs/configuring/cache.md, docs/configuring/database.md, docs/configuring/reverse_proxy.md, docs/configuring/storage.md
=> Fix broken links

CHANGES/646.bugfix, controllers/pulp/api.go, controllers/pulp/content.go, controllers/pulp/utils.go, controllers/pulp/worker.go
=> Fix node_selector reconciliation logic

README.md
=> Add operator doc page in README.md

.dockerignore, Makefile, bundle.Dockerfile, bundle/manifests/pulp-operator-manager-config_v1_configmap.yaml, bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/manifests/repo-manager.pulpproject.org_pulps.yaml, bundle/metadata/annotations.yaml, bundle/tests/scorecard/config.yaml, config/default/manager_auth_proxy_patch.yaml, config/manager/controller_manager_config.yaml, config/manager/manager.yaml, config/scorecard/patches/basic.config.yaml, config/scorecard/patches/olm.config.yaml
=> Upgrade sdk to 1.24.1

CHANGES/646.bugfix, controllers/pulp/pdb.go
=> Fix pdb reconciliation logic

CHANGES/646.bugfix, controllers/pulp/api.go, controllers/pulp/content.go, controllers/pulp/redis.go, controllers/pulp/worker.go
=> Fix strategy reconciliation logic

.ci/scripts/pulp_tests.sh, .github/workflows/ci.yml, .github/workflows/scripts/show_logs.sh, CHANGES/678.misc, config/samples/simple.ingress.yaml
=> Add ingress test on CI

controllers/pulp/web.go
=> Fix pulp-web deployment reconciliation

CHANGES/646.bugfix, api/v1alpha1/pulp_types.go, config/crd/bases/repo-manager.pulpproject.org_pulps.yaml, controllers/pulp/README.md, controllers/pulp/controller.go, controllers/pulp/status.go, controllers/pulp/utils.go
=> Set Cache.ExternalCacheSecret immutable

CHANGES/646.bugfix, api/v1alpha1/repo_manager_types.go, config/crd/bases/repo-manager.pulpproject.org_pulps.yaml, controllers/repo_manager/README.md, controllers/repo_manager/redis.go
=> Fix Cache.RedisPort field update/reconciliation

docs/pulp.md
=> Fix broken doc

.ci/scripts/backup_and_restore.sh, .ci/scripts/kubelinter.sh, .ci/scripts/local.sh, .github/workflows/ci.yml, .github/workflows/scripts/show_logs.sh, CHANGES/692.misc, Makefile, controllers/utils.go
=> Add command to rename kind

CHANGES/709.bugfix, config/rbac/role.yaml, controllers/repo_manager/controller.go
=> Add ingressclass clusterrole

.github/workflows/ci.yml, Makefile, controllers/repo_manager/controller_test.go
=> Fix building renamed kind images

.github/workflows/ci.yml, .github/workflows/pr.yml, config/samples/pulpproject_v1beta1_pulp_cr.s6.ci.yaml, up.sh
=> Fix testing the s6 pulp/pulp images

CHANGES/722.feature, api/v1alpha1/repo_manager_types.go, config/crd/bases/repo-manager.pulpproject.org_pulps.yaml, controllers/repo_manager/ingress.go, controllers/repo_manager/route.go
=> Omit nginx configs from Pulp CR

CHANGES/714.bugfix, controllers/repo_manager/ingress.go
=> Ensure ingress status conditions

CHANGES/729.feature, controllers/repo_manager/route.go
=> Add goroutines for routes provisioning

CHANGES/669.feature, controllers/repo_manager/controller.go
=> Check non-ocp env config with ingress_type:route

.github/workflows/ci.yml
https://github.com/pulp/pulp-operator/actions/runs/3388117555/jobs/5630006402
=> Fix publishing operator image

.github/ISSUE_TEMPLATE/demo.md, .github/ISSUE_TEMPLATE/task.md
=> Add demo option when filing issues

CHANGES/747.bugfix, controllers/repo_manager/controller.go
=> Modify controller RequeueAfter condition order

CHANGES/755.bugfix, controllers/repo_manager/utils.go
=> Fix ingress type assertion

bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/manager/manager.yaml
The capabilities spec is a field from securityContext. 
[noissue]
=> Fix an issue with wrong indentation

CHANGES/756.bugfix, controllers/repo_manager/controller_test.go, controllers/repo_manager/route.go, controllers/repo_manager/status.go
=> Update ERROR message as DEBUG

.github/workflows/ci.yml, CHANGES/763.misc
=> Add CI containerized scenario

CHANGES/672.bugfix, CHANGES/735.bugfix, CHANGES/736.bugfix, CHANGES/747.bugfix, CHANGES/751.bugfix, CHANGES/755.bugfix, CHANGES/756.bugfix, CHANGES/763.misc, Makefile, bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, docs/CHANGES.md
=> Release 1.0.0-alpha.2

config/manager/manager.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, controllers/backup/controller.go, controllers/repo_manager/controller_test.go, controllers/repo_manager/database.go, controllers/repo_manager/redis.go, controllers/restore/utils.go
=> Ensure full path

Makefile
Add support for podman in Makefile [noissue]
Signed-off-by: Leo Ochoa [lochoa@redhat.com](mailto:lochoa@redhat.com)
=> Add support for podman in Makefile

api/v1alpha1/repo_manager_types.go, api/v1alpha1/zz_generated.deepcopy.go, bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/manifests/repo-manager.pulpproject.org_pulps.yaml, config/crd/bases/repo-manager.pulpproject.org_pulps.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, controllers/repo_manager/README.md, controllers/repo_manager/route.go
We need to be able to add annotations
https://github.com/operate-first/apps/pull/2615
https://pulp.operate-first.cloud/pulp/api/v3/status/
=> Make route annotations editable

controllers/repo_manager/api.go, controllers/repo_manager/utils.go
=> Refactor pulp-api provisioning method

CHANGES/676.feature, api/v1alpha1/repo_manager_types.go, bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/manifests/repo-manager.pulpproject.org_pulps.yaml, config/crd/bases/repo-manager.pulpproject.org_pulps.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, controllers/repo_manager/README.md, controllers/repo_manager/ingress.go
=> Add Ingress TLS secret

controllers/repo_manager/content.go
=> Refactor pulp-content provisioning method

controllers/repo_manager/worker.go
=> Refactor pulp-worker provisioning method

CHANGES/770.bugfix, controllers/repo_manager/controller.go
=> Make web available when ingress isn't nginx

controllers/repo_manager/api.go, controllers/repo_manager/utils.go
=> Create a random fernet key

CHANGES/550.feature, CHANGES/676.feature, CHANGES/770.bugfix, CHANGES/782.feature, Makefile, bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, docs/CHANGES.md
=> Release 1.0.0-alpha.3

controllers/repo_manager/controller.go, controllers/repo_manager/utils.go
=> Add needsRequeue func to controller

controllers/repo_manager/utils.go
=> Remove reconcileObject method repetitive blocks

Dockerfile, Makefile, bundle.Dockerfile, bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, bundle/tests/scorecard/config.yaml, config/scorecard/patches/basic.config.yaml, config/scorecard/patches/olm.config.yaml
=> Upgrade SDK to 1.25.2

CHANGES/792.doc, docs/configuring/unmanaged.md, docs/faq.md, mkdocs.yml
=> Document unmanaged state process

CHANGES/800.feature, api/v1alpha1/repo_manager_types.go, bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/manifests/repo-manager.pulpproject.org_pulps.yaml, config/crd/bases/repo-manager.pulpproject.org_pulps.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, controllers/repo_manager/README.md, controllers/repo_manager/route.go, controllers/repo_manager/utils.go, docs/configuring/routes.md
=> Add field to configure route custom cert

CHANGES/674.feature, api/v1alpha1/repo_manager_types.go, config/crd/bases/repo-manager.pulpproject.org_pulps.yaml, config/samples/simple.ingress.yaml, controllers/repo_manager/README.md, controllers/repo_manager/controller.go, controllers/repo_manager/ingress.go, controllers/repo_manager/status.go, controllers/repo_manager/utils.go, controllers/restore/deploy.go, controllers/utils.go, docs/configuring/reverse_proxy.md
=> Add a field to set IngressClass name

controllers/repo_manager/controller.go
This update is meant to run .status.conditions[] update block only in the first execution (when Pulp-Operator-Finished-Execution condition does not exist). 
The old logic was wrong. The way it was, every time the operator was with the condition "Pulp-Operator-Finished-Execution: false" it would enter the block.
[noissue]
=> Fix a wrong validation to update .status field

controllers/repo_manager/status.go
Added "block" wg to make sure that goroutines finished before proceeding. 
This is helpful to synchronize the update events and avoid racing condition issues with other tasks from different goroutines. 
[noissue]
=> Add waitgroup to sync goroutines

controllers/repo_manager/controller.go, controllers/repo_manager/ingress.go, controllers/repo_manager/status.go
=> Handle OCP Ingress

.github/stale.yml
=> Fix stalebot config

CHANGES/807.bugfix, controllers/repo_manager/controller_test.go
=> Fix envtest evaluating wrong data

CHANGES/674.feature, CHANGES/792.doc, CHANGES/796.misc, CHANGES/800.feature, CHANGES/807.bugfix, Makefile, bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, docs/CHANGES.md
=> Release 1.0.0-alpha.4

CHANGES/808.bugfix, controllers/backup/pulp_dir.go, controllers/restore/pulp_dir.go
=> Fix a permission/ownership error on bkp/restore

controllers/repo_manager/api.go, controllers/repo_manager/content.go, controllers/repo_manager/utils.go
=> Refactor service reconciliation

.github/workflows/ci.yml
=> Add slack warning

CHANGES/771.doc, docs/configuring/reverse_proxy.md, docs/ingress.yaml
=> Add steps to manually create ingress

CHANGES/765.doc, api/v1alpha1/repo_manager_backup_types.go, api/v1alpha1/repo_manager_restore_types.go, api/v1alpha1/repo_manager_types.go, config/crd/bases/repo-manager.pulpproject.org_pulpbackups.yaml, config/crd/bases/repo-manager.pulpproject.org_pulprestores.yaml, config/crd/bases/repo-manager.pulpproject.org_pulps.yaml, controllers/backup/README.md, controllers/restore/README.md, docs/backup_and_restore/config_running.md, docs/backup_and_restore/overview.md, docs/faq.md, mkdocs.yml
=> Document backup and restore procedures

.ci/prow/openshift-test.sh, config/samples/pulpproject_v1beta1_pulp_cr.ocp.ci.yaml
=> Fix prow job

.ci/scripts/local.sh, CHANGES/821.feature, Makefile, api/v1alpha1/repo_manager_types.go, config/crd/bases/repo-manager.pulpproject.org_pulps.yaml, config/rbac/role.yaml, controllers/repo_manager/README.md, controllers/repo_manager/api.go, controllers/repo_manager/controller.go, controllers/repo_manager/galaxy.go, controllers/repo_manager/utils.go, docs/configuring/galaxy.md, mkdocs.yml
=> Add galaxy default EE

CHANGES/829.bugfix, controllers/repo_manager/controller_test.go, controllers/repo_manager/status.go
=> Fixes update status deadlock (ingress resources)

CHANGES/830.bugfix, controllers/repo_manager/utils.go
=> Fix wrong marshaling of pulp settings

CHANGES/834.bugfix, controllers/repo_manager/api.go
=> Fix subpath mount for container token pub key

.ci/scripts/galaxy_ng-tests.sh, .ci/scripts/pulp_tests.sh, CHANGES/836.bugfix, controllers/repo_manager/api.go, controllers/repo_manager/route.go, controllers/repo_manager/utils.go
=> Fix wrong settings for token server

CHANGES/848.feature, controllers/repo_manager/controller_test.go, controllers/repo_manager/database.go
=> Modify pgsql mountpoint to keep compatibility

CHANGES/675.bugfix, CHANGES/765.doc, CHANGES/771.doc, CHANGES/808.bugfix, CHANGES/821.feature, CHANGES/827.doc, CHANGES/829.bugfix, CHANGES/830.bugfix, CHANGES/834.bugfix, CHANGES/836.bugfix, CHANGES/848.feature, Makefile, bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/manifests/repo-manager.pulpproject.org_pulpbackups.yaml, bundle/manifests/repo-manager.pulpproject.org_pulprestores.yaml, bundle/manifests/repo-manager.pulpproject.org_pulps.yaml, config/manager/kustomization.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, docs/CHANGES.md
=> Release 1.0.0-alpha.5

CHANGES/852.bugfix, controllers/repo_manager/api.go, controllers/repo_manager/controller.go
=> Define container auth secret name based on Pulp CR

api/v1alpha1/repo_manager_types.go, bundle/manifests/repo-manager.pulpproject.org_pulps.yaml, config/crd/bases/repo-manager.pulpproject.org_pulps.yaml, controllers/repo_manager/README.md
=> Modify Api field(required) and default replicas=1

Makefile
There are tasks in ci-operator that are failing because golang is not installed. This commit will verify if golang is found in the common install path and install it if necessary.
ref: #773
[noissue]
=> Add target to install golang in Makefile

.github/workflows/ci.yml, CHANGES/858.misc
=> Add pipeline job to test upgrade

.ci/scripts/galaxy_ng-tests.sh, .ci/scripts/pulp_tests.sh, config/samples/galaxy.azure.ci.yaml, config/samples/galaxy.s3.ci.yaml, config/samples/galaxy.yaml, config/samples/pulpproject_v1beta1_pulp_cr.galaxy.ocp.ci.yaml
=> Modify pulp-cli installation method for tests

.ci/prow/openshift-test.sh
=> Temp workaround to an issue in ci-operator

.ci/prow/openshift-test.sh
=> More output to prow script and fix container name

.ci/prow/openshift-test.sh
=> Keep showing logs in case of error in prow script

.ci/prow/openshift-test.sh
=> Provision galaxy secrets in prow env tests

api/v1alpha1/repo_manager_backup_types.go, api/v1alpha1/repo_manager_restore_types.go, api/v1alpha1/repo_manager_types.go, bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/manifests/repo-manager.pulpproject.org_pulpbackups.yaml, bundle/manifests/repo-manager.pulpproject.org_pulprestores.yaml, bundle/manifests/repo-manager.pulpproject.org_pulps.yaml, config/crd/bases/repo-manager.pulpproject.org_pulpbackups.yaml, config/crd/bases/repo-manager.pulpproject.org_pulprestores.yaml, config/crd/bases/repo-manager.pulpproject.org_pulps.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml
=> Update SDK markers

.ci/scripts/galaxy_ng-tests.sh, .ci/scripts/pulp_tests.sh, config/samples/pulpproject_v1beta1_pulp_cr.galaxy.azure.ci.yaml, config/samples/pulpproject_v1beta1_pulp_cr.galaxy.ci.yaml, config/samples/pulpproject_v1beta1_pulp_cr.galaxy.s3.ci.yaml, roles/common/tasks/create_app_sa.yml, roles/common/tasks/main.yml, roles/postgres/tasks/main.yml
The operator execution was not converging because of multiple tasks modifying the same resource in different ways.
ref: https://issues.redhat.com/browse/AAP-7866
[noissue]
=> Fix reconciliation and pipeline issues

.github/workflows/ci.yml, CHANGES/935.misc, Dockerfile, Makefile, go.mod
=> Bump golang version and bind it with GH action

CHANGES/928.bugfix, CHANGES/929.bugfix, roles/pulp-api/tasks/main.yml, roles/pulp-api/tasks/signing_service.yml, roles/pulp-api/templates/pulp-api.deployment.yaml.j2, roles/pulp-content/templates/pulp-content.deployment.yaml.j2, roles/pulp-worker/templates/pulp-worker.deployment.yaml.j2
=> Signing script mount point

CHANGES/824.doc, docs/configuring/storage.md
closes #824
ref: #946
ref: #945
=> Add more info to emptyDir doc and storage samples

.github/workflows/ci.yml, CHANGES/521.bugfix, controllers/repo_manager/api.go, controllers/repo_manager/controller.go, controllers/repo_manager/utils.go, controllers/utils.go, docs/configuring/secrets.md
=> Add pulp-server secret reconciliation logic

.github/workflows/ci.yml
Instead of running the same set of integration tests multiple times, create a new job to run it once.
[noissue]
=> Run only a single instance of integration tests

CHANGES/973.feature, controllers/repo_manager/api.go
=> Add a log message before restarting pods

CHANGES/521.bugfix, CHANGES/666.doc, CHANGES/824.doc, CHANGES/969.feature, CHANGES/973.feature, Makefile, bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, docs/CHANGES.md, main.go
=> Release alpha 7

CHANGES/987.bugfix, Makefile, bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, docs/CHANGES.md, main.go
=> Release alpha 8

.ci/scripts/kind_with_registry.sh, .github/workflows/ci.yml, CHANGES/986.misc, Makefile
=> Add a workflow to test OLM bundle upgrades

CHANGES/984.misc, Makefile, PROJECT, bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, config/samples/kustomization.yaml, config/samples/repo-manager.pulpproject.org_v1alpha1_pulp.yaml, config/samples/repo-manager.pulpproject.org_v1beta1_pulp.yaml, config/samples/repo-manager.pulpproject.org_v1beta2_pulp.yaml, config/samples/repo-manager_v1beta1_pulpbackup.yaml, config/samples/repo-manager_v1beta1_pulprestore.yaml, config/samples/repo-manager_v1beta2_pulpbackup.yaml, config/samples/repo-manager_v1beta2_pulprestore.yaml
Fix the wrong configurations in PROJECT file that was impacting the execution of
```
operator-sdk generate kustomize manifests
Generating kustomize files in config/manifests
WARN[0000] Skipping definitions parsing for API {}: Go type not found
WARN[0000] Skipping definitions parsing for API {}: Go type not found
...
```
and also the missing/wrong samples in csv.
fixes: #984
=> Fix the warnings from `make bundle` execution

bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml
=> [ansible] csv: Fix redis typo

.github/workflows/ci.yml, .github/workflows/scripts/show_logs.sh, CHANGES/993.misc, controllers/repo_manager/api.go, controllers/repo_manager/controller_test.go, main.go
=> Update tests to decrease liveness probe errors

CHANGES/937.bugfix, controllers/backup/controller.go, main.go
=> Update date format on backup dirs

bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/manifests/pulp.pulpproject.org_pulps.yaml, config/crd/bases/pulpproject_v1beta1_pulp_crd.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, roles/redis/defaults/main.yml, roles/redis/templates/redis.pvc.yaml.j2
RFE to make redis storage size configurable
=> Fulfill RFE to configure redis storage size

CHANGES/1016.feature, apis/repo-manager.pulpproject.org/v1beta1/pulp_types.go, apis/repo-manager.pulpproject.org/v1beta2/pulp_types.go, bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/manifests/repo-manager.pulpproject.org_pulps.yaml, config/crd/bases/repo-manager.pulpproject.org_pulps.yaml, controllers/repo_manager/README.md, controllers/repo_manager/redis.go, main.go
=> Add redis_storage_size for ansible compatibility

Makefile, controllers/deployment.go, controllers/repo_manager/controller_test.go, controllers/telemetry.go, controllers/utils.go, main.go
=> Refactor deployment to avoid code repetition

controllers/repo_manager/controller.go, controllers/repo_manager/utils.go, main.go
=> Create indexerFunc to reduce code duplication

roles/backup/tasks/postgres.yml, roles/restore/tasks/postgres.yml
=> Fix external db backup

docs/configuring/networking/reverse_proxy.md
=> [DOC] Fix path to the ingress.yaml sample

.github/workflows/scripts/show_logs.sh, CHANGES/991.feature, apis/repo-manager.pulpproject.org/v1beta2/pulp_types.go, bundle/manifests/repo-manager.pulpproject.org_pulps.yaml, config/crd/bases/repo-manager.pulpproject.org_pulps.yaml, controllers/deployment.go, controllers/repo_manager/README.md, controllers/repo_manager/content.go, controllers/repo_manager/controller.go, controllers/repo_manager/controller_test.go, controllers/repo_manager/job.go, controllers/repo_manager/status.go, controllers/repo_manager/utils.go, controllers/utils.go, main.go
=> Create jobs to run migrations

controllers/repo_manager/controller.go, controllers/repo_manager/precheck.go, controllers/repo_manager/utils.go, main.go
=> Add a precheck function to run validations

.ci/scripts/galaxy_ng-tests.sh, .github/workflows/ci.yml, CHANGES/946.feature, bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/samples/galaxy.azure.ci.yaml, config/samples/galaxy.s3.ci.yaml, config/samples/galaxy.yaml, config/samples/repo-manager.pulpproject.org_v1beta2_pulp.yaml, controllers/repo_manager/precheck.go, main.go
=> Verify file_storage definition w/out storage_class

CHANGES/1048.bugfix, controllers/repo_manager/utils.go
=> Fixes bug related to CONTENT_ORIGIN scheme always being https

CHANGES/1041.misc, controllers/deployment.go, controllers/ocp/deployment.go, controllers/ocp/ingress.go, controllers/ocp/route.go, controllers/repo_manager/api.go, controllers/repo_manager/content.go, controllers/repo_manager/ingress.go, controllers/repo_manager/redis.go, controllers/repo_manager/web.go, controllers/repo_manager/worker.go, controllers/utils.go, main.go
=> Modify pulp resources reconciliation logic

CHANGES/1040.feature, apis/repo-manager.pulpproject.org/v1beta2/pulp_backup_types.go, apis/repo-manager.pulpproject.org/v1beta2/pulp_types.go, bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/manifests/repo-manager.pulpproject.org_pulpbackups.yaml, bundle/manifests/repo-manager.pulpproject.org_pulps.yaml, config/crd/bases/repo-manager.pulpproject.org_pulpbackups.yaml, config/crd/bases/repo-manager.pulpproject.org_pulps.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, controllers/backup/README.md, controllers/backup/controller.go, controllers/backup/secret.go, controllers/backup/utils.go, controllers/repo_manager/README.md, controllers/repo_manager/api.go, controllers/repo_manager/controller.go, controllers/repo_manager/precheck.go, controllers/repo_manager/status.go, controllers/repo_manager/utils.go, controllers/restore/secret.go, docs/configuring/secrets.md, main.go
=> Add the `pulp_secret_key` field

.github/workflows/ci.yml, CHANGES/1006.feature, CHANGES/1008.doc, CHANGES/1016.feature, CHANGES/1019.feature, CHANGES/1040.feature, CHANGES/1041.misc, CHANGES/1048.bugfix, CHANGES/884.misc, CHANGES/885.removal, CHANGES/917.bugfix, CHANGES/918.bugfix, CHANGES/923.bugfix, CHANGES/937.bugfix, CHANGES/946.feature, CHANGES/984.misc, CHANGES/986.misc, CHANGES/991.feature, CHANGES/993.misc, Makefile, bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, docs/CHANGES.md, main.go
=> Release alpha 9

docs/configuring/networking/reverse_proxy.md
=> [DOC] Add more info for manual ingress config

.github/workflows/ci.yml
=> Update GH actions/setup-go to fix warning msgs

.github/workflows/ci.yml
=> Update helm ci workflow to use the current source code

CHANGES/1060.feature, apis/repo-manager.pulpproject.org/v1beta2/pulp_types.go, apis/repo-manager.pulpproject.org/v1beta2/zz_generated.deepcopy.go, bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/manifests/repo-manager.pulpproject.org_pulps.yaml, config/crd/bases/repo-manager.pulpproject.org_pulps.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, controllers/deployment.go, controllers/repo_manager/README.md, controllers/repo_manager/api.go, controllers/repo_manager/controller.go, controllers/repo_manager/job.go, controllers/repo_manager/precheck.go, controllers/repo_manager/secret.go, controllers/repo_manager/status.go, controllers/repo_manager/utils.go, docs/configuring/content_checksums.md, main.go, mkdocs.yml
=> Add job to handle allowed_content_checksums update

bundle/manifests/pulp-operator.clusterserviceversion.yaml
Fix so that the field is for text instead of getting the storage class
=> Edit pulp redis storage size

CHANGES/1074.feature, controllers/repo_manager/job.go, main.go
=> Set k8s job names based on Pulp CR name

.github/workflows/ci.yml, CHANGES/1044.removal, CHANGES/1057.bugfix, CHANGES/1060.feature, CHANGES/1066.bugfix, CHANGES/1074.feature, CHANGES/817.removal, Makefile, bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, docs/CHANGES.md, main.go
=> Release beta 1

CHANGES/1081.bugfix, controllers/deployment.go, controllers/repo_manager/controller_test.go, controllers/telemetry.go, main.go
=> Update container entrypoint with new pulp version

CHANGES/1078.doc, docs/configuring/reset_admin_pwd.md
=> Update reset admin password documentation

CHANGES/1079.feature, apis/repo-manager.pulpproject.org/v1beta2/pulp_types.go, apis/repo-manager.pulpproject.org/v1beta2/zz_generated.deepcopy.go, bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/manifests/repo-manager.pulpproject.org_pulps.yaml, config/crd/bases/repo-manager.pulpproject.org_pulps.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, controllers/repo_manager/README.md, controllers/repo_manager/rbac.go
=> Add fields to set Pulp SA labels/annotations

docs/install/ha.md, mkdocs.yml
=> Add documentation for HA Pulp installation

docs/backup_and_restore/cronjob.md, mkdocs.yml
=> Document the steps to create a cronjob to run bkps

CHANGES/1102.bugfix, controllers/deployment.go, controllers/telemetry.go, main.go
=> Fix KubeAPIWarningLogger PodSecurity warning msgs

CHANGES/742.doc, docs/configuring/database.md
=> Add doc steps to rotate db fields encryption key

CHANGES/1101.misc, controllers/deployment.go, controllers/repo_manager/controller_test.go, main.go
=> Modify the entrypoint of pulpcore containers

.github/workflows/ci.yml, CHANGES/1042.feature, CHANGES/1078.doc, CHANGES/1079.feature, CHANGES/1081.bugfix, CHANGES/1098.bugfix, CHANGES/1101.misc, CHANGES/1102.bugfix, CHANGES/742.doc, Makefile, bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, docs/CHANGES.md, main.go
=> Release beta 2

config/samples/pulpcon-sample.yaml
=> Add a sample for pulpcon presentation

CHANGES/1122.bugfix, controllers/repo_manager/secret.go, main.go
=> Fix an issue in pulp_settings defining tuples

controllers/repo_manager/job.go, main.go
=> Add an OwnerReference to the jobs for gc

controllers/repo_manager/controller.go, controllers/repo_manager/ingress.go, controllers/repo_manager/status.go, main.go
=> Refactor pulpStatus method

controllers/repo_manager/controller.go, main.go
=> Better organize Reconcile method tasks

.ci/scripts/kubelinter.sh, CHANGES/1132.bugfix, bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/samples/galaxy.azure.ci.yaml, config/samples/galaxy.s3.ci.yaml, config/samples/galaxy.yaml, controllers/repo_manager/secret.go, main.go
=> Make addCustomPulpSettings function more "generic"

controllers/deployment.go
Include ImagePullPolicy in initcontainers
=> [noissue] Include ImagePullPolicy in initcontainers

controllers/repo_manager/api.go, controllers/repo_manager/controller.go, controllers/repo_manager/secret.go, main.go
=> Move k8s secrets tasks away from api.go

controllers/repo_manager/api.go, controllers/repo_manager/controller.go, controllers/repo_manager/pvc.go, main.go
=> Move file storage tasks away from api.go

.ci/assets/kubernetes/signing_scripts.yaml, .github/workflows/ci.yml, CHANGES/939.bugfix, apis/repo-manager.pulpproject.org/v1beta2/pulp_types.go, apis/repo-manager.pulpproject.org/v1beta2/zz_generated.deepcopy.go, bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/manifests/repo-manager.pulpproject.org_pulps.yaml, config/crd/bases/repo-manager.pulpproject.org_pulps.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, config/samples/galaxy.azure.ci.yaml, config/samples/galaxy.s3.ci.yaml, config/samples/galaxy.yaml, controllers/backup/secret.go, controllers/deployment.go, controllers/repo_manager/README.md, controllers/repo_manager/controller.go, controllers/repo_manager/job.go, controllers/repo_manager/precheck.go, controllers/repo_manager/utils.go, controllers/restore/secret.go, controllers/settings/jobs.go, controllers/utils.go, main.go
=> Fix signing services

CHANGES/1145.doc, README.md, docs/index.md
=> Update doc index page

CHANGES/1003.doc, docs/configuring/metadata_signing.md, mkdocs.yml
=> Add doc to configure the metadata signing

controllers/repo_manager/job.go, main.go
=> Remove code duplication for k8s job definition

CHANGES/1154.bugfix, controllers/repo_manager/ldap.go, main.go
=> Update pulp-server import from django-auth-ldap

.ci/prow/openshift-test.sh, bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, config/samples/pulpproject_v1beta1_pulp_cr.galaxy.ocp.ci.yaml, config/samples/simple-external-cache.yaml, config/samples/simple-external-db.yaml, config/samples/simple-sso.yaml
It was breaking prow tests.
[noissue]
=> Update signing_scripts_configmap deprecated field

CHANGES/1163.doc, docs/configuring/pulp_settings.md, docs/configuring/secrets.md, mkdocs.yml
=> Add a doc section explaining `pulp_settings` field

.github/workflows/ci.yml, config/samples/simple-external-db.yaml
=> Add a pipeline job to test external db config

go.mod, go.sum
=> Bump github.com/go-logr/logr from 1.3.0 to 1.4.1

.ci/scripts/pulp_tests.sh, .github/workflows/k8s_versions.yml, .github/workflows/scripts/show_logs.sh, config/eks-anywhere/eks/1.27/kustomization.yaml, config/eks-anywhere/eks/1.27/mgmt.yaml, config/eks-anywhere/eks/1.28/kustomization.yaml, config/eks-anywhere/eks/1.28/mgmt.yaml, config/eks-anywhere/eks/1.29/kustomization.yaml, config/eks-anywhere/eks/1.29/mgmt.yaml, config/eks-anywhere/eks/base/eks.yaml, config/eks-anywhere/eks/base/kustomization.yaml, config/eks-anywhere/localpath-sc/kustomization.yaml, config/eks-anywhere/localpath-sc/local-path-storage.yaml, config/samples/k8s_versions_ci.yaml
=> Add GH pipelines to run in different k8s versions

CHANGES/1190.feature, CHANGES/1192.bugfix, CHANGES/1192.misc
Adjust my CHANGES snippets from #1199 and #1193 to follow: https://docs.pulpproject.org/pulpcore/contributing/git.html#changelog-update
=> [noissue] adjust CHANGES snippets to follow project standards

.github/workflows/ci.yml, CHANGES/1161.feature, CHANGES/1163.doc, CHANGES/1190.feature, CHANGES/1192.misc, Makefile, bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, docs/CHANGES.md, main.go
=> Release beta 4

.ci/scripts/ldap_config.sh
=> Update python path in ldap CI workflow

.ci/scripts/backup_and_restore.sh, .ci/scripts/pulp_tests.sh, go.mod, go.sum
=> Update some configs to fix ci errors

CHANGES/1221.bugfix, apis/repo-manager.pulpproject.org/v1beta2/pulp_types.go, bundle/manifests/pulp-operator.clusterserviceversion.yaml, bundle/manifests/repo-manager.pulpproject.org_pulps.yaml, config/crd/bases/repo-manager.pulpproject.org_pulps.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml, controllers/repo_manager/README.md, controllers/repo_manager/secret.go, docs/configuring/logLevel.md, staging_docs/admin/guides/configurations/logLevel.md
=> Add a field to enable pulpcore debug logging

CHANGES/1232.feature, apis/repo-manager.pulpproject.org/v1beta2/pulp_types.go, bundle/manifests/repo-manager.pulpproject.org_pulps.yaml, config/crd/bases/repo-manager.pulpproject.org_pulps.yaml, controllers/deployment.go, controllers/repo_manager/README.md, controllers/repo_manager/utils.go, controllers/utils.go, main.go
=> Run a migration job if the storage type changed

CHANGES/1239.bugfix, controllers/deployment.go, controllers/repo_manager/job.go, controllers/utils.go
=> Mount the signing scripts in pulpcore pods

.github/workflows/ci.yml, .github/workflows/docs-ci.yml, CHANGES/+new-docs-ci.misc, Makefile, doc_requirements.txt
Related to: https://github.com/pulp/pulp-docs/issues/31
[noissue]
=> Add unified docs-ci

staging_docs/admin/guides/configurations/pod_resources.md
=> Adds docs on setting pod resources.

docs/overrides/main.html, mkdocs.yml
See https://github.com/pulp/pulp-docs/issues/33
[noissue]
---
=> Add deprecation banner to old docs

go.mod, go.sum
=> Bump github.com/go-logr/logr from 1.4.1 to 1.4.2

.github/workflows/ci.yml
=> Run tidy in lint job CI to update go.mod

.github/workflows/ci.yml, CHANGES/1315.bugfix, controllers/backup/controller.go, controllers/deployment.go, controllers/repo_manager/database.go, controllers/repo_manager/job.go, controllers/repo_manager/redis.go, controllers/repo_manager/web.go, controllers/restore/pulp_dir.go, controllers/restore/utils.go, controllers/telemetry.go, controllers/utils.go, go.mod
=> Add PodSecurityStandards to the web deployment and jobs

CHANGES/1319.bugfix, controllers/repo_manager/database.go, controllers/repo_manager/rbac.go, controllers/repo_manager/redis.go
=> Fix database/cache pods SCC error in OCP

CHANGES/1294.bugfix, controllers/repo_manager/job.go, controllers/repo_manager/status.go
=> Run reset-admin-password on reinstallation

roles/pulp-routes/tasks/main.yml
Change apiVersion to avoid failure while deploying hub
Resolves:
https://issues.redhat.com/browse/AAP-28261
=> Change apiVersion to avoid failure while deploying hub with HCO deployed

CHANGES/1339.bugfix, controllers/repo_manager/ingress.go, main.go
=> Allow adding custom annotations to NGINX ingresses

CHANGES/1067.removal, controllers/repo_manager/precheck.go, main.go
=> Remove version mismatch check if web replicas=0

CHANGES/1356.bugfix, bundle/manifests/repo-manager.pulpproject.org_pulpbackups.yaml, bundle/manifests/repo-manager.pulpproject.org_pulps.yaml, config/crd/bases/repo-manager.pulpproject.org_pulpbackups.yaml, config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
=> Update manifests with the `ipv6_disabled` field

.ci/scripts/pulp_container/remote.sh
Modify the test script from dockerhub to ghcr to avoid the "429 Too Many Requests" issue.
=> Change the container registry to ghcr.io

CHANGES/1345.removal, config/samples/galaxy.azure.ci.yaml, config/samples/galaxy.s3.ci.yaml, config/samples/pulpproject_v1beta1_pulp_cr.galaxy.ocp.ci.yaml, config/samples/pulpproject_v1beta1_pulp_cr.ocp.ci.yaml, config/samples/simple-external-cache.yaml, controllers/deployment.go, controllers/repo_manager/controller_test.go, controllers/repo_manager/database.go, controllers/repo_manager/precheck.go, controllers/repo_manager/utils.go, controllers/utils.go, docs/configuring/database.md, docs/configuring/storage.md, go.mod, staging_docs/admin/guides/configurations/database.md, staging_docs/admin/guides/configurations/storage.md
=>  Remove `emptyDir` support 

.github/workflows/docs-ci.yml
=> Update GH runner for docs CI

.github/pull_request_template.md, README.md, docs/architecture.md, docs/contributing.md, mkdocs.yml
=> Fix some documentation links

config/samples/k8s_versions_ci.yaml, config/samples/ldap.yaml, config/samples/simple-external-db.yaml, config/samples/simple-test.yaml, config/samples/simple-with-reduced-migration-cpu.yaml, config/samples/simple.ingress.yaml, config/samples/simple.yaml, config/samples/telemetry.yaml, controllers/repo_manager/web.go
=> Update pulp-web CM to adapt pulp-oci-image change

.github/workflows/release.yml
=> Fix release CI workflow image tag

staging_docs/admin/guides/configurations/networking/reverse_proxy.md
=> Fix ingress doc with custom_pulp_settings format

.github/workflows/ci.yml, .github/workflows/upgrade.yml, bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/manifests/bases/pulp-operator.clusterserviceversion.yaml
=> Update "Upgrade CI" workflow configuration

.ci/prow/openshift-test.sh
=> Update prow script (openshift-test.sh)

staging_docs/admin/guides/configurations/reset_admin_pwd.md, staging_docs/admin/guides/configurations/sample_configs.md, staging_docs/admin/guides/configurations/storage.md
=> Add sample configs docs

.github/workflows/upgrade.yml, CHANGES/1411.fix, Makefile, bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, controllers/repo_manager/secret.go, controllers/repo_manager/utils.go, controllers/settings/secrets.go
=> Fix duplicated configs with custom_pulp_settings

.ci/scripts/prepare-object-storage.sh
=> Update `mc config` command in CI script

.ci/scripts/backup_and_restore.sh, .ci/scripts/ldap_config.sh, .ci/scripts/pulp_ansible/setup.sh, .ci/scripts/pulp_tests.sh, .github/actions/pre-reqs/action.yml, .github/workflows/ci.yml, .github/workflows/k8s_versions.yml
=> Upgrade python version to fix CI issues

.github/workflows/upgrade.yml, CHANGES.md, CHANGES/1411.bugfix, CHANGES/1466.bugfix, CHANGES/1522.feature, Makefile, bundle/manifests/pulp-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml
=> Release 1.1.0

docs/admin/guides/install/helm.md
=> Updated deployment via pulp-operator to an working example
